var charData = {
"ਕ": { cp: "U+0A15", name: "GURMUKHI LETTER KA", mark: false },
"ਖ": { cp: "U+0A16", name: "GURMUKHI LETTER KHA", mark: false },
"ਗ": { cp: "U+0A17", name: "GURMUKHI LETTER GA", mark: false },
"ਘ": { cp: "U+0A18", name: "GURMUKHI LETTER GHA", mark: false },
"ਙ": { cp: "U+0A19", name: "GURMUKHI LETTER NGA", mark: false },
"ਚ": { cp: "U+0A1A", name: "GURMUKHI LETTER CA", mark: false },
"ਛ": { cp: "U+0A1B", name: "GURMUKHI LETTER CHA", mark: false },
"ਜ": { cp: "U+0A1C", name: "GURMUKHI LETTER JA", mark: false },
"ਝ": { cp: "U+0A1D", name: "GURMUKHI LETTER JHA", mark: false },
"ਞ": { cp: "U+0A1E", name: "GURMUKHI LETTER NYA", mark: false },
"ਟ": { cp: "U+0A1F", name: "GURMUKHI LETTER TTA", mark: false },
"ਠ": { cp: "U+0A20", name: "GURMUKHI LETTER TTHA", mark: false },
"ਡ": { cp: "U+0A21", name: "GURMUKHI LETTER DDA", mark: false },
"ਢ": { cp: "U+0A22", name: "GURMUKHI LETTER DDHA", mark: false },
"ਣ": { cp: "U+0A23", name: "GURMUKHI LETTER NNA", mark: false },
"ਤ": { cp: "U+0A24", name: "GURMUKHI LETTER TA", mark: false },
"ਥ": { cp: "U+0A25", name: "GURMUKHI LETTER THA", mark: false },
"ਦ": { cp: "U+0A26", name: "GURMUKHI LETTER DA", mark: false },
"ਧ": { cp: "U+0A27", name: "GURMUKHI LETTER DHA", mark: false },
"ਨ": { cp: "U+0A28", name: "GURMUKHI LETTER NA", mark: false },
"ਪ": { cp: "U+0A2A", name: "GURMUKHI LETTER PA", mark: false },
"ਫ": { cp: "U+0A2B", name: "GURMUKHI LETTER PHA", mark: false },
"ਬ": { cp: "U+0A2C", name: "GURMUKHI LETTER BA", mark: false },
"ਭ": { cp: "U+0A2D", name: "GURMUKHI LETTER BHA", mark: false },
"ਮ": { cp: "U+0A2E", name: "GURMUKHI LETTER MA", mark: false },
"ਯ": { cp: "U+0A2F", name: "GURMUKHI LETTER YA", mark: false },
"ਰ": { cp: "U+0A30", name: "GURMUKHI LETTER RA", mark: false },
"ਲ": { cp: "U+0A32", name: "GURMUKHI LETTER LA", mark: false },
"ਵ": { cp: "U+0A35", name: "GURMUKHI LETTER VA", mark: false },
"ਸ਼": { cp: "U+0A38 U+0A3C", name: "GURMUKHI LETTER SA, GURMUKHI SIGN NUKTA", mark: false },
"ਸ": { cp: "U+0A38", name: "GURMUKHI LETTER SA", mark: false },
"ਹ": { cp: "U+0A39", name: "GURMUKHI LETTER HA", mark: false },
"੍": { cp: "U+0A4D", name: "GURMUKHI SIGN VIRAMA", mark: true },
"ਖ਼": { cp: "U+0A16 U+0A3C", name: "GURMUKHI LETTER KHA, GURMUKHI SIGN NUKTA", mark: false },
"ਗ਼": { cp: "U+0A17 U+0A3C", name: "GURMUKHI LETTER GA, GURMUKHI SIGN NUKTA", mark: false },
"ੜ": { cp: "U+0A5C", name: "GURMUKHI LETTER RRA", mark: false },
"ਲ਼": { cp: "U+0A32 U+0A3C", name: "GURMUKHI LETTER LA, GURMUKHI SIGN NUKTA", mark: false },
"ਫ਼": { cp: "U+0A2B U+0A3C", name: "GURMUKHI LETTER PHA, GURMUKHI SIGN NUKTA", mark: false },
"ਜ਼": { cp: "U+0A1C U+0A3C", name: "GURMUKHI LETTER JA, GURMUKHI SIGN NUKTA", mark: false },
"੦": { cp: "U+0A66", name: "GURMUKHI DIGIT ZERO", mark: false },
"੧": { cp: "U+0A67", name: "GURMUKHI DIGIT ONE", mark: false },
"੨": { cp: "U+0A68", name: "GURMUKHI DIGIT TWO", mark: false },
"੩": { cp: "U+0A69", name: "GURMUKHI DIGIT THREE", mark: false },
"੪": { cp: "U+0A6A", name: "GURMUKHI DIGIT FOUR", mark: false },
"੫": { cp: "U+0A6B", name: "GURMUKHI DIGIT FIVE", mark: false },
"੬": { cp: "U+0A6C", name: "GURMUKHI DIGIT SIX", mark: false },
"੭": { cp: "U+0A6D", name: "GURMUKHI DIGIT SEVEN", mark: false },
"੮": { cp: "U+0A6E", name: "GURMUKHI DIGIT EIGHT", mark: false },
"੯": { cp: "U+0A6F", name: "GURMUKHI DIGIT NINE", mark: false },
"ੴ": { cp: "U+0A74", name: "GURMUKHI EK ONKAR", mark: false },
"ੲ": { cp: "U+0A72", name: "GURMUKHI IRI", mark: false },
"ੳ": { cp: "U+0A73", name: "GURMUKHI URA", mark: false },
"☬": { cp: "U+262C", name: "ADI SHAKTI", mark: false },
"ੰ": { cp: "U+0A70", name: "GURMUKHI TIPPI", mark: true },
"ੱ": { cp: "U+0A71", name: "GURMUKHI ADDAK", mark: true },
"ਁ": { cp: "U+0A01", name: "GURMUKHI SIGN ADAK BINDI", mark: true },
"ਂ": { cp: "U+0A02", name: "GURMUKHI SIGN BINDI", mark: true },
"ਃ": { cp: "U+0A03", name: "GURMUKHI SIGN VISARGA", mark: true },
"਼": { cp: "U+0A3C", name: "GURMUKHI SIGN NUKTA", mark: true },
"।": { cp: "U+0964", name: "DEVANAGARI DANDA", mark: false },
"॥": { cp: "U+0965", name: "DEVANAGARI DOUBLE DANDA", mark: false },
"ਅ": { cp: "U+0A05", name: "GURMUKHI LETTER A", mark: false },
"ਾ": { cp: "U+0A3E", name: "GURMUKHI VOWEL SIGN AA", mark: true },
"ਆ": { cp: "U+0A06", name: "GURMUKHI LETTER AA", mark: false },
"ਿ": { cp: "U+0A3F", name: "GURMUKHI VOWEL SIGN I", mark: true },
"ਇ": { cp: "U+0A07", name: "GURMUKHI LETTER I", mark: false },
"ੀ": { cp: "U+0A40", name: "GURMUKHI VOWEL SIGN II", mark: true },
"ਈ": { cp: "U+0A08", name: "GURMUKHI LETTER II", mark: false },
"ੁ": { cp: "U+0A41", name: "GURMUKHI VOWEL SIGN U", mark: true },
"ਉ": { cp: "U+0A09", name: "GURMUKHI LETTER U", mark: false },
"ੂ": { cp: "U+0A42", name: "GURMUKHI VOWEL SIGN UU", mark: true },
"ਊ": { cp: "U+0A0A", name: "GURMUKHI LETTER UU", mark: false },
"ੇ": { cp: "U+0A47", name: "GURMUKHI VOWEL SIGN EE", mark: true },
"ਏ": { cp: "U+0A0F", name: "GURMUKHI LETTER EE", mark: false },
"ੈ": { cp: "U+0A48", name: "GURMUKHI VOWEL SIGN AI", mark: true },
"ਐ": { cp: "U+0A10", name: "GURMUKHI LETTER AI", mark: false },
"ੋ": { cp: "U+0A4B", name: "GURMUKHI VOWEL SIGN OO", mark: true },
"ਓ": { cp: "U+0A13", name: "GURMUKHI LETTER OO", mark: false },
"ੌ": { cp: "U+0A4C", name: "GURMUKHI VOWEL SIGN AU", mark: true },
"ਔ": { cp: "U+0A14", name: "GURMUKHI LETTER AU", mark: false },
"ੑ": { cp: "U+0A51", name: "GURMUKHI SIGN UDAAT", mark: true },
"ੵ": { cp: "U+0A75", name: "GURMUKHI SIGN YAKASH", mark: true },
"\u0A36": { cp: "U+0A36", name: "GURMUKHI LETTER SHA", mark: false },
"\u0A59": { cp: "U+0A59", name: "GURMUKHI LETTER KHHA", mark: false },
"\u0A5A": { cp: "U+0A5A", name: "GURMUKHI LETTER GHHA", mark: false },
"\u0A5B": { cp: "U+0A5B", name: "GURMUKHI LETTER ZA", mark: false },
"\u0A5E": { cp: "U+0A5E", name: "GURMUKHI LETTER FA", mark: false },
"\u0A33": { cp: "U+0A33", name: "GURMUKHI LETTER LLA", mark: false },
end: {}
}


// define character to insert as a base for combining characters
var _combiningBase = '\u00A0'
var _combiningBase = ''



function localInitialise () {

	}



var _h = {
"A05": ['A06','A10','A14','A18'],
"A06": ['A05','A10','A14','A18'],
"A07": ['A08','A0F','A72','A1D','A23'],
"A08": ['A07','A0F','A72','A1D','A23'],
"A09": ['A0A','A13','A73'],
"A0A": ['A09','A13','A73'],
"A0F": ['A08','A07','A72','A1D','A23'],
"A10": ['A06','A05','A14','A18'],
"A13": ['A0A','A09','A73','A74'],
"A14": ['A06','A10','A05','A18'],
"A15": ['A2D'],
"A16": ['A2A','A59','A25','A27','A16A3C'],
"A16A3C": ['A16','A59','A2A','A27'],
"A17": ['A17A3C','A5A','A39'],
"A17A3C": ['A17','A5A','A39'],
"A18": ['A06','A10','A14','A05'],
"A19": ["A1B"],
"A1A": ['A22','A30','A39'],
"A1C": ['A5B','A1CA3C'],
"A1CA3C": ['A5B','A1C'],
"A1D": ['A1E'],
"A1E": ['A1D','A35'],
"A20": ["A30","A28"],
"A21": ["A5C"],
"A22": ["A26","A1A","A2B","A5E","A2BA3C"],
"A23": ["A0F"],
"A24": ['A69'],
"A25": ['A16','A59','A2A','A27','A16A3C'],
"A26": ['A22','A1A'],
"A27": ['A16','A59','A25','A2A','A16A3C'],
"A28": ['A20'],
"A2A": ['A16','A59','A25','A27','A16A3C'],
"A2B": ['A5E','A22','A2BA3C'],
"A2BA3C": ['A5E','A22','A2B'],
"A2C": ['A72','A0F'],
"A2D": ['A15'],
"A2E": ['A36','A38','A38A3C'],
"A2F": ['A27'],
"A30": ['A39','A1A','A20','A17'],
"A32": ['A33','A32A3C'],
"A32A3C": ['A33','A32'],
"A33": ['A32A3C','A32'],
"A35": ['A1E','A1D'],
"A36": ['A38','A2E'],
"A38": ['A36','A2E','A38A3C'],
"A38A3C": ['A36','A2E','A38'],
"A39": ['A30','A1A','A17'],
"A59": ['A16','A2A','A25','A27','A16A3C'],
"A5A": ['A17A3C','A17','A39'],
"A5B": ['A1C','A1CA3C'],
"A5C": ['A21','A69'],
"A5E": ['A2B','A2BA3C','A22'],
"A6B": ['A2A','A2E'],
"A6C": ['A69'],
"A6E": ['A6F'],
"A6F": ['A6E'],
"A69": ['A21','A2D','A6E'],
"A72": ['A08','A0F','A07','A1D','A23'],
"A73": ['A0A','A13','A09'],
"A74": ['A09','A73','A13'],
"A": ['A'],
"A": ['A'],
"A": ['A'],
"A": ['A'],


end: {}
}




