var extlang = [{type:"extlang",subtag:"aao",description:"Algerian Saharan Arabic",added:"2009-07-29",preferredvalue:"aao",prefix:"ar",macrolanguage:"ar"},
{type:"extlang",subtag:"abh",description:"Tajiki Arabic",added:"2009-07-29",preferredvalue:"abh",prefix:"ar",macrolanguage:"ar"},
{type:"extlang",subtag:"abv",description:"Baharna Arabic",added:"2009-07-29",preferredvalue:"abv",prefix:"ar",macrolanguage:"ar"},
{type:"extlang",subtag:"acm",description:"Mesopotamian Arabic",added:"2009-07-29",preferredvalue:"acm",prefix:"ar",macrolanguage:"ar"},
{type:"extlang",subtag:"acq",description:"Ta'izzi-Adeni Arabic",added:"2009-07-29",preferredvalue:"acq",prefix:"ar",macrolanguage:"ar"},
{type:"extlang",subtag:"acw",description:"Hijazi Arabic",added:"2009-07-29",preferredvalue:"acw",prefix:"ar",macrolanguage:"ar"},
{type:"extlang",subtag:"acx",description:"Omani Arabic",added:"2009-07-29",preferredvalue:"acx",prefix:"ar",macrolanguage:"ar"},
{type:"extlang",subtag:"acy",description:"Cypriot Arabic",added:"2009-07-29",preferredvalue:"acy",prefix:"ar",macrolanguage:"ar"},
{type:"extlang",subtag:"adf",description:"Dhofari Arabic",added:"2009-07-29",preferredvalue:"adf",prefix:"ar",macrolanguage:"ar"},
{type:"extlang",subtag:"ads",description:"Adamorobe Sign Language",added:"2009-07-29",preferredvalue:"ads",prefix:"sgn"},
{type:"extlang",subtag:"aeb",description:"Tunisian Arabic",added:"2009-07-29",preferredvalue:"aeb",prefix:"ar",macrolanguage:"ar"},
{type:"extlang",subtag:"aec",description:"Saidi Arabic",added:"2009-07-29",preferredvalue:"aec",prefix:"ar",macrolanguage:"ar"},
{type:"extlang",subtag:"aed",description:"Argentine Sign Language",added:"2009-07-29",preferredvalue:"aed",prefix:"sgn"},
{type:"extlang",subtag:"aen",description:"Armenian Sign Language",added:"2009-07-29",preferredvalue:"aen",prefix:"sgn"},
{type:"extlang",subtag:"afb",description:"Gulf Arabic",added:"2009-07-29",preferredvalue:"afb",prefix:"ar",macrolanguage:"ar"},
{type:"extlang",subtag:"afg",description:"Afghan Sign Language",added:"2009-07-29",preferredvalue:"afg",prefix:"sgn"},
{type:"extlang",subtag:"ajp",description:"South Levantine Arabic",added:"2009-07-29",preferredvalue:"ajp",prefix:"ar",macrolanguage:"ar"},
{type:"extlang",subtag:"apc",description:"North Levantine Arabic",added:"2009-07-29",preferredvalue:"apc",prefix:"ar",macrolanguage:"ar"},
{type:"extlang",subtag:"apd",description:"Sudanese Arabic",added:"2009-07-29",preferredvalue:"apd",prefix:"ar",macrolanguage:"ar"},
{type:"extlang",subtag:"arb",description:"Standard Arabic",added:"2009-07-29",preferredvalue:"arb",prefix:"ar",macrolanguage:"ar"},
{type:"extlang",subtag:"arq",description:"Algerian Arabic",added:"2009-07-29",preferredvalue:"arq",prefix:"ar",macrolanguage:"ar"},
{type:"extlang",subtag:"ars",description:"Najdi Arabic",added:"2009-07-29",preferredvalue:"ars",prefix:"ar",macrolanguage:"ar"},
{type:"extlang",subtag:"ary",description:"Moroccan Arabic",added:"2009-07-29",preferredvalue:"ary",prefix:"ar",macrolanguage:"ar"},
{type:"extlang",subtag:"arz",description:"Egyptian Arabic",added:"2009-07-29",preferredvalue:"arz",prefix:"ar",macrolanguage:"ar"},
{type:"extlang",subtag:"ase",description:"American Sign Language",added:"2009-07-29",preferredvalue:"ase",prefix:"sgn"},
{type:"extlang",subtag:"asf",description:"Australian Sign Language",added:"2009-07-29",preferredvalue:"asf",prefix:"sgn"},
{type:"extlang",subtag:"asp",description:"Algerian Sign Language",added:"2009-07-29",preferredvalue:"asp",prefix:"sgn"},
{type:"extlang",subtag:"asq",description:"Austrian Sign Language",added:"2009-07-29",preferredvalue:"asq",prefix:"sgn"},
{type:"extlang",subtag:"asw",description:"Australian Aborigines Sign Language",added:"2009-07-29",preferredvalue:"asw",prefix:"sgn"},
{type:"extlang",subtag:"auz",description:"Uzbeki Arabic",added:"2009-07-29",preferredvalue:"auz",prefix:"ar",macrolanguage:"ar"},
{type:"extlang",subtag:"avl",description:"Eastern Egyptian Bedawi Arabic",added:"2009-07-29",preferredvalue:"avl",prefix:"ar",macrolanguage:"ar"},
{type:"extlang",subtag:"ayh",description:"Hadrami Arabic",added:"2009-07-29",preferredvalue:"ayh",prefix:"ar",macrolanguage:"ar"},
{type:"extlang",subtag:"ayl",description:"Libyan Arabic",added:"2009-07-29",preferredvalue:"ayl",prefix:"ar",macrolanguage:"ar"},
{type:"extlang",subtag:"ayn",description:"Sanaani Arabic",added:"2009-07-29",preferredvalue:"ayn",prefix:"ar",macrolanguage:"ar"},
{type:"extlang",subtag:"ayp",description:"North Mesopotamian Arabic",added:"2009-07-29",preferredvalue:"ayp",prefix:"ar",macrolanguage:"ar"},
{type:"extlang",subtag:"bbz",description:"Babalia Creole Arabic",added:"2009-07-29",preferredvalue:"bbz",prefix:"ar",macrolanguage:"ar"},
{type:"extlang",subtag:"bfi",description:"British Sign Language",added:"2009-07-29",preferredvalue:"bfi",prefix:"sgn"},
{type:"extlang",subtag:"bfk",description:"Ban Khor Sign Language",added:"2009-07-29",preferredvalue:"bfk",prefix:"sgn"},
{type:"extlang",subtag:"bjn",description:"Banjar",added:"2009-07-29",preferredvalue:"bjn",prefix:"ms",macrolanguage:"ms"},
{type:"extlang",subtag:"bog",description:"Bamako Sign Language",added:"2009-07-29",preferredvalue:"bog",prefix:"sgn"},
{type:"extlang",subtag:"bqn",description:"Bulgarian Sign Language",added:"2009-07-29",preferredvalue:"bqn",prefix:"sgn"},
{type:"extlang",subtag:"bqy",description:"Bengkala Sign Language",added:"2009-07-29",preferredvalue:"bqy",prefix:"sgn"},
{type:"extlang",subtag:"btj",description:"Bacanese Malay",added:"2009-07-29",preferredvalue:"btj",prefix:"ms",macrolanguage:"ms"},
{type:"extlang",subtag:"bve",description:"Berau Malay",added:"2009-07-29",preferredvalue:"bve",prefix:"ms",macrolanguage:"ms"},
{type:"extlang",subtag:"bvl",description:"Bolivian Sign Language",added:"2009-07-29",preferredvalue:"bvl",prefix:"sgn"},
{type:"extlang",subtag:"bvu",description:"Bukit Malay",added:"2009-07-29",preferredvalue:"bvu",prefix:"ms",macrolanguage:"ms"},
{type:"extlang",subtag:"bzs",description:"Brazilian Sign Language",added:"2009-07-29",preferredvalue:"bzs",prefix:"sgn"},
{type:"extlang",subtag:"cdo",description:"Min Dong Chinese",added:"2009-07-29",preferredvalue:"cdo",prefix:"zh",macrolanguage:"zh"},
{type:"extlang",subtag:"cds",description:"Chadian Sign Language",added:"2009-07-29",preferredvalue:"cds",prefix:"sgn"},
{type:"extlang",subtag:"cjy",description:"Jinyu Chinese",added:"2009-07-29",preferredvalue:"cjy",prefix:"zh",macrolanguage:"zh"},
{type:"extlang",subtag:"cmn",description:"Mandarin Chinese",added:"2009-07-29",preferredvalue:"cmn",prefix:"zh",macrolanguage:"zh"},
{type:"extlang",subtag:"coa",description:"Cocos Islands Malay",added:"2009-07-29",preferredvalue:"coa",prefix:"ms",macrolanguage:"ms"},
{type:"extlang",subtag:"cpx",description:"Pu-Xian Chinese",added:"2009-07-29",preferredvalue:"cpx",prefix:"zh",macrolanguage:"zh"},
{type:"extlang",subtag:"csc",description:"Catalan Sign Language, Lengua de señas catalana, Llengua de Signes Catalana",added:"2009-07-29",preferredvalue:"csc",prefix:"sgn"},
{type:"extlang",subtag:"csd",description:"Chiangmai Sign Language",added:"2009-07-29",preferredvalue:"csd",prefix:"sgn"},
{type:"extlang",subtag:"cse",description:"Czech Sign Language",added:"2009-07-29",preferredvalue:"cse",prefix:"sgn"},
{type:"extlang",subtag:"csf",description:"Cuba Sign Language",added:"2009-07-29",preferredvalue:"csf",prefix:"sgn"},
{type:"extlang",subtag:"csg",description:"Chilean Sign Language",added:"2009-07-29",preferredvalue:"csg",prefix:"sgn"},
{type:"extlang",subtag:"csl",description:"Chinese Sign Language",added:"2009-07-29",preferredvalue:"csl",prefix:"sgn"},
{type:"extlang",subtag:"csn",description:"Colombian Sign Language",added:"2009-07-29",preferredvalue:"csn",prefix:"sgn"},
{type:"extlang",subtag:"csq",description:"Croatia Sign Language",added:"2009-07-29",preferredvalue:"csq",prefix:"sgn"},
{type:"extlang",subtag:"csr",description:"Costa Rican Sign Language",added:"2009-07-29",preferredvalue:"csr",prefix:"sgn"},
{type:"extlang",subtag:"czh",description:"Huizhou Chinese",added:"2009-07-29",preferredvalue:"czh",prefix:"zh",macrolanguage:"zh"},
{type:"extlang",subtag:"czo",description:"Min Zhong Chinese",added:"2009-07-29",preferredvalue:"czo",prefix:"zh",macrolanguage:"zh"},
{type:"extlang",subtag:"doq",description:"Dominican Sign Language",added:"2009-07-29",preferredvalue:"doq",prefix:"sgn"},
{type:"extlang",subtag:"dse",description:"Dutch Sign Language",added:"2009-07-29",preferredvalue:"dse",prefix:"sgn"},
{type:"extlang",subtag:"dsl",description:"Danish Sign Language",added:"2009-07-29",preferredvalue:"dsl",prefix:"sgn"},
{type:"extlang",subtag:"dup",description:"Duano",added:"2009-07-29",preferredvalue:"dup",prefix:"ms",macrolanguage:"ms"},
{type:"extlang",subtag:"ecs",description:"Ecuadorian Sign Language",added:"2009-07-29",preferredvalue:"ecs",prefix:"sgn"},
{type:"extlang",subtag:"esl",description:"Egypt Sign Language",added:"2009-07-29",preferredvalue:"esl",prefix:"sgn"},
{type:"extlang",subtag:"esn",description:"Salvadoran Sign Language",added:"2009-07-29",preferredvalue:"esn",prefix:"sgn"},
{type:"extlang",subtag:"eso",description:"Estonian Sign Language",added:"2009-07-29",preferredvalue:"eso",prefix:"sgn"},
{type:"extlang",subtag:"eth",description:"Ethiopian Sign Language",added:"2009-07-29",preferredvalue:"eth",prefix:"sgn"},
{type:"extlang",subtag:"fcs",description:"Quebec Sign Language",added:"2009-07-29",preferredvalue:"fcs",prefix:"sgn"},
{type:"extlang",subtag:"fse",description:"Finnish Sign Language",added:"2009-07-29",preferredvalue:"fse",prefix:"sgn"},
{type:"extlang",subtag:"fsl",description:"French Sign Language",added:"2009-07-29",preferredvalue:"fsl",prefix:"sgn"},
{type:"extlang",subtag:"fss",description:"Finland-Swedish Sign Language, finlandssvenskt teckenspråk, suomenruotsalainen viittomakieli",added:"2009-07-29",preferredvalue:"fss",prefix:"sgn"},
{type:"extlang",subtag:"gan",description:"Gan Chinese",added:"2009-07-29",preferredvalue:"gan",prefix:"zh",macrolanguage:"zh"},
{type:"extlang",subtag:"gds",description:"Ghandruk Sign Language",added:"2012-08-12",preferredvalue:"gds",prefix:"sgn"},
{type:"extlang",subtag:"gom",description:"Goan Konkani",added:"2009-07-29",preferredvalue:"gom",prefix:"kok",macrolanguage:"kok"},
{type:"extlang",subtag:"gse",description:"Ghanaian Sign Language",added:"2009-07-29",preferredvalue:"gse",prefix:"sgn"},
{type:"extlang",subtag:"gsg",description:"German Sign Language",added:"2009-07-29",preferredvalue:"gsg",prefix:"sgn"},
{type:"extlang",subtag:"gsm",description:"Guatemalan Sign Language",added:"2009-07-29",preferredvalue:"gsm",prefix:"sgn"},
{type:"extlang",subtag:"gss",description:"Greek Sign Language",added:"2009-07-29",preferredvalue:"gss",prefix:"sgn"},
{type:"extlang",subtag:"gus",description:"Guinean Sign Language",added:"2009-07-29",preferredvalue:"gus",prefix:"sgn"},
{type:"extlang",subtag:"hab",description:"Hanoi Sign Language",added:"2009-07-29",preferredvalue:"hab",prefix:"sgn"},
{type:"extlang",subtag:"haf",description:"Haiphong Sign Language",added:"2009-07-29",preferredvalue:"haf",prefix:"sgn"},
{type:"extlang",subtag:"hak",description:"Hakka Chinese",added:"2009-07-29",preferredvalue:"hak",prefix:"zh",macrolanguage:"zh"},
{type:"extlang",subtag:"hds",description:"Honduras Sign Language",added:"2009-07-29",preferredvalue:"hds",prefix:"sgn"},
{type:"extlang",subtag:"hji",description:"Haji",added:"2009-07-29",preferredvalue:"hji",prefix:"ms",macrolanguage:"ms"},
{type:"extlang",subtag:"hks",description:"Hong Kong Sign Language, Heung Kong Sau Yue",added:"2009-07-29",preferredvalue:"hks",prefix:"sgn"},
{type:"extlang",subtag:"hos",description:"Ho Chi Minh City Sign Language",added:"2009-07-29",preferredvalue:"hos",prefix:"sgn"},
{type:"extlang",subtag:"hps",description:"Hawai'i Sign Language (HSL), Hawai'i Pidgin Sign Language",added:"2009-07-29",preferredvalue:"hps",prefix:"sgn"},
{type:"extlang",subtag:"hsh",description:"Hungarian Sign Language",added:"2009-07-29",preferredvalue:"hsh",prefix:"sgn"},
{type:"extlang",subtag:"hsl",description:"Hausa Sign Language",added:"2009-07-29",preferredvalue:"hsl",prefix:"sgn"},
{type:"extlang",subtag:"hsn",description:"Xiang Chinese",added:"2009-07-29",preferredvalue:"hsn",prefix:"zh",macrolanguage:"zh"},
{type:"extlang",subtag:"icl",description:"Icelandic Sign Language",added:"2009-07-29",preferredvalue:"icl",prefix:"sgn"},
{type:"extlang",subtag:"iks",description:"Inuit Sign Language",added:"2015-02-12",preferredvalue:"iks",prefix:"sgn"},
{type:"extlang",subtag:"ils",description:"International Sign",added:"2009-07-29",preferredvalue:"ils",prefix:"sgn"},
{type:"extlang",subtag:"inl",description:"Indonesian Sign Language",added:"2009-07-29",preferredvalue:"inl",prefix:"sgn"},
{type:"extlang",subtag:"ins",description:"Indian Sign Language",added:"2009-07-29",preferredvalue:"ins",prefix:"sgn"},
{type:"extlang",subtag:"ise",description:"Italian Sign Language",added:"2009-07-29",preferredvalue:"ise",prefix:"sgn"},
{type:"extlang",subtag:"isg",description:"Irish Sign Language",added:"2009-07-29",preferredvalue:"isg",prefix:"sgn"},
{type:"extlang",subtag:"isr",description:"Israeli Sign Language",added:"2009-07-29",preferredvalue:"isr",prefix:"sgn"},
{type:"extlang",subtag:"jak",description:"Jakun",added:"2009-07-29",preferredvalue:"jak",prefix:"ms",macrolanguage:"ms"},
{type:"extlang",subtag:"jax",description:"Jambi Malay",added:"2009-07-29",preferredvalue:"jax",prefix:"ms",macrolanguage:"ms"},
{type:"extlang",subtag:"jcs",description:"Jamaican Country Sign Language",added:"2009-07-29",preferredvalue:"jcs",prefix:"sgn"},
{type:"extlang",subtag:"jhs",description:"Jhankot Sign Language",added:"2009-07-29",preferredvalue:"jhs",prefix:"sgn"},
{type:"extlang",subtag:"jls",description:"Jamaican Sign Language",added:"2010-03-11",preferredvalue:"jls",prefix:"sgn"},
{type:"extlang",subtag:"jos",description:"Jordanian Sign Language",added:"2009-07-29",preferredvalue:"jos",prefix:"sgn"},
{type:"extlang",subtag:"jsl",description:"Japanese Sign Language",added:"2009-07-29",preferredvalue:"jsl",prefix:"sgn"},
{type:"extlang",subtag:"jus",description:"Jumla Sign Language",added:"2009-07-29",preferredvalue:"jus",prefix:"sgn"},
{type:"extlang",subtag:"kgi",description:"Selangor Sign Language",added:"2009-07-29",preferredvalue:"kgi",prefix:"sgn"},
{type:"extlang",subtag:"knn",description:"Konkani (individual language)",added:"2009-07-29",preferredvalue:"knn",prefix:"kok",macrolanguage:"kok"},
{type:"extlang",subtag:"kvb",description:"Kubu",added:"2009-07-29",preferredvalue:"kvb",prefix:"ms",macrolanguage:"ms"},
{type:"extlang",subtag:"kvk",description:"Korean Sign Language",added:"2009-07-29",preferredvalue:"kvk",prefix:"sgn"},
{type:"extlang",subtag:"kvr",description:"Kerinci",added:"2009-07-29",preferredvalue:"kvr",prefix:"ms",macrolanguage:"ms"},
{type:"extlang",subtag:"kxd",description:"Brunei",added:"2009-07-29",preferredvalue:"kxd",prefix:"ms",macrolanguage:"ms"},
{type:"extlang",subtag:"lbs",description:"Libyan Sign Language",added:"2009-07-29",preferredvalue:"lbs",prefix:"sgn"},
{type:"extlang",subtag:"lce",description:"Loncong, Sekak",added:"2009-07-29",preferredvalue:"lce",prefix:"ms",macrolanguage:"ms"},
{type:"extlang",subtag:"lcf",description:"Lubu",added:"2009-07-29",preferredvalue:"lcf",prefix:"ms",macrolanguage:"ms"},
{type:"extlang",subtag:"liw",description:"Col",added:"2009-07-29",preferredvalue:"liw",prefix:"ms",macrolanguage:"ms"},
{type:"extlang",subtag:"lls",description:"Lithuanian Sign Language",added:"2009-07-29",preferredvalue:"lls",prefix:"sgn"},
{type:"extlang",subtag:"lsg",description:"Lyons Sign Language",added:"2009-07-29",preferredvalue:"lsg",prefix:"sgn"},
{type:"extlang",subtag:"lsl",description:"Latvian Sign Language",added:"2009-07-29",preferredvalue:"lsl",prefix:"sgn"},
{type:"extlang",subtag:"lso",description:"Laos Sign Language",added:"2009-07-29",preferredvalue:"lso",prefix:"sgn"},
{type:"extlang",subtag:"lsp",description:"Panamanian Sign Language, Lengua de Señas Panameñas",added:"2009-07-29",preferredvalue:"lsp",prefix:"sgn"},
{type:"extlang",subtag:"lst",description:"Trinidad and Tobago Sign Language",added:"2009-07-29",preferredvalue:"lst",prefix:"sgn"},
{type:"extlang",subtag:"lsy",description:"Mauritian Sign Language",added:"2010-03-11",preferredvalue:"lsy",prefix:"sgn"},
{type:"extlang",subtag:"ltg",description:"Latgalian",added:"2010-03-11",preferredvalue:"ltg",prefix:"lv",macrolanguage:"lv"},
{type:"extlang",subtag:"lvs",description:"Standard Latvian",added:"2010-03-11",preferredvalue:"lvs",prefix:"lv",macrolanguage:"lv"},
{type:"extlang",subtag:"lzh",description:"Literary Chinese",added:"2009-07-29",preferredvalue:"lzh",prefix:"zh",macrolanguage:"zh"},
{type:"extlang",subtag:"max",description:"North Moluccan Malay",added:"2009-07-29",preferredvalue:"max",prefix:"ms",macrolanguage:"ms"},
{type:"extlang",subtag:"mdl",description:"Maltese Sign Language",added:"2009-07-29",preferredvalue:"mdl",prefix:"sgn"},
{type:"extlang",subtag:"meo",description:"Kedah Malay",added:"2009-07-29",preferredvalue:"meo",prefix:"ms",macrolanguage:"ms"},
{type:"extlang",subtag:"mfa",description:"Pattani Malay",added:"2009-07-29",preferredvalue:"mfa",prefix:"ms",macrolanguage:"ms"},
{type:"extlang",subtag:"mfb",description:"Bangka",added:"2009-07-29",preferredvalue:"mfb",prefix:"ms",macrolanguage:"ms"},
{type:"extlang",subtag:"mfs",description:"Mexican Sign Language",added:"2009-07-29",preferredvalue:"mfs",prefix:"sgn"},
{type:"extlang",subtag:"min",description:"Minangkabau",added:"2009-07-29",preferredvalue:"min",prefix:"ms",macrolanguage:"ms"},
{type:"extlang",subtag:"mnp",description:"Min Bei Chinese",added:"2009-07-29",preferredvalue:"mnp",prefix:"zh",macrolanguage:"zh"},
{type:"extlang",subtag:"mqg",description:"Kota Bangun Kutai Malay",added:"2009-07-29",preferredvalue:"mqg",prefix:"ms",macrolanguage:"ms"},
{type:"extlang",subtag:"mre",description:"Martha's Vineyard Sign Language",added:"2009-07-29",preferredvalue:"mre",prefix:"sgn"},
{type:"extlang",subtag:"msd",description:"Yucatec Maya Sign Language",added:"2009-07-29",preferredvalue:"msd",prefix:"sgn"},
{type:"extlang",subtag:"msi",description:"Sabah Malay",added:"2009-07-29",preferredvalue:"msi",prefix:"ms",macrolanguage:"ms"},
{type:"extlang",subtag:"msr",description:"Mongolian Sign Language",added:"2009-07-29",preferredvalue:"msr",prefix:"sgn"},
{type:"extlang",subtag:"mui",description:"Musi",added:"2009-07-29",preferredvalue:"mui",prefix:"ms",macrolanguage:"ms"},
{type:"extlang",subtag:"mzc",description:"Madagascar Sign Language",added:"2009-07-29",preferredvalue:"mzc",prefix:"sgn"},
{type:"extlang",subtag:"mzg",description:"Monastic Sign Language",added:"2009-07-29",preferredvalue:"mzg",prefix:"sgn"},
{type:"extlang",subtag:"mzy",description:"Mozambican Sign Language",added:"2009-07-29",preferredvalue:"mzy",prefix:"sgn"},
{type:"extlang",subtag:"nan",description:"Min Nan Chinese",added:"2009-07-29",preferredvalue:"nan",prefix:"zh",macrolanguage:"zh"},
{type:"extlang",subtag:"nbs",description:"Namibian Sign Language",added:"2009-07-29",preferredvalue:"nbs",prefix:"sgn"},
{type:"extlang",subtag:"ncs",description:"Nicaraguan Sign Language",added:"2009-07-29",preferredvalue:"ncs",prefix:"sgn"},
{type:"extlang",subtag:"nsi",description:"Nigerian Sign Language",added:"2009-07-29",preferredvalue:"nsi",prefix:"sgn"},
{type:"extlang",subtag:"nsl",description:"Norwegian Sign Language",added:"2009-07-29",preferredvalue:"nsl",prefix:"sgn"},
{type:"extlang",subtag:"nsp",description:"Nepalese Sign Language",added:"2009-07-29",preferredvalue:"nsp",prefix:"sgn"},
{type:"extlang",subtag:"nsr",description:"Maritime Sign Language",added:"2009-07-29",preferredvalue:"nsr",prefix:"sgn"},
{type:"extlang",subtag:"nzs",description:"New Zealand Sign Language",added:"2009-07-29",preferredvalue:"nzs",prefix:"sgn"},
{type:"extlang",subtag:"okl",description:"Old Kentish Sign Language",added:"2009-07-29",preferredvalue:"okl",prefix:"sgn"},
{type:"extlang",subtag:"orn",description:"Orang Kanaq",added:"2009-07-29",preferredvalue:"orn",prefix:"ms",macrolanguage:"ms"},
{type:"extlang",subtag:"ors",description:"Orang Seletar",added:"2009-07-29",preferredvalue:"ors",prefix:"ms",macrolanguage:"ms"},
{type:"extlang",subtag:"pel",description:"Pekal",added:"2009-07-29",preferredvalue:"pel",prefix:"ms",macrolanguage:"ms"},
{type:"extlang",subtag:"pga",description:"Sudanese Creole Arabic",added:"2009-07-29",preferredvalue:"pga",prefix:"ar",macrolanguage:"ar"},
{type:"extlang",subtag:"pgz",description:"Papua New Guinean Sign Language",added:"2016-05-30",preferredvalue:"pgz",prefix:"sgn"},
{type:"extlang",subtag:"pks",description:"Pakistan Sign Language",added:"2009-07-29",preferredvalue:"pks",prefix:"sgn"},
{type:"extlang",subtag:"prl",description:"Peruvian Sign Language",added:"2009-07-29",preferredvalue:"prl",prefix:"sgn"},
{type:"extlang",subtag:"prz",description:"Providencia Sign Language",added:"2009-07-29",preferredvalue:"prz",prefix:"sgn"},
{type:"extlang",subtag:"psc",description:"Persian Sign Language",added:"2009-07-29",preferredvalue:"psc",prefix:"sgn"},
{type:"extlang",subtag:"psd",description:"Plains Indian Sign Language",added:"2009-07-29",preferredvalue:"psd",prefix:"sgn"},
{type:"extlang",subtag:"pse",description:"Central Malay",added:"2009-07-29",preferredvalue:"pse",prefix:"ms",macrolanguage:"ms"},
{type:"extlang",subtag:"psg",description:"Penang Sign Language",added:"2009-07-29",preferredvalue:"psg",prefix:"sgn"},
{type:"extlang",subtag:"psl",description:"Puerto Rican Sign Language",added:"2009-07-29",preferredvalue:"psl",prefix:"sgn"},
{type:"extlang",subtag:"pso",description:"Polish Sign Language",added:"2009-07-29",preferredvalue:"pso",prefix:"sgn"},
{type:"extlang",subtag:"psp",description:"Philippine Sign Language",added:"2009-07-29",preferredvalue:"psp",prefix:"sgn"},
{type:"extlang",subtag:"psr",description:"Portuguese Sign Language",added:"2009-07-29",preferredvalue:"psr",prefix:"sgn"},
{type:"extlang",subtag:"pys",description:"Paraguayan Sign Language, Lengua de Señas del Paraguay",added:"2010-03-11",preferredvalue:"pys",prefix:"sgn"},
{type:"extlang",subtag:"rms",description:"Romanian Sign Language",added:"2009-07-29",preferredvalue:"rms",prefix:"sgn"},
{type:"extlang",subtag:"rsi",description:"Rennellese Sign Language",added:"2009-07-29",preferredvalue:"rsi",prefix:"sgn"},
{type:"extlang",subtag:"rsl",description:"Russian Sign Language",added:"2009-07-29",preferredvalue:"rsl",prefix:"sgn"},
{type:"extlang",subtag:"rsm",description:"Miriwoong Sign Language",added:"2016-05-30",preferredvalue:"rsm",prefix:"sgn"},
{type:"extlang",subtag:"sdl",description:"Saudi Arabian Sign Language",added:"2009-07-29",preferredvalue:"sdl",prefix:"sgn"},
{type:"extlang",subtag:"sfb",description:"Langue des signes de Belgique Francophone, French Belgian Sign Language",added:"2009-07-29",preferredvalue:"sfb",prefix:"sgn"},
{type:"extlang",subtag:"sfs",description:"South African Sign Language",added:"2009-07-29",preferredvalue:"sfs",prefix:"sgn"},
{type:"extlang",subtag:"sgg",description:"Swiss-German Sign Language",added:"2009-07-29",preferredvalue:"sgg",prefix:"sgn"},
{type:"extlang",subtag:"sgx",description:"Sierra Leone Sign Language",added:"2009-07-29",preferredvalue:"sgx",prefix:"sgn"},
{type:"extlang",subtag:"shu",description:"Chadian Arabic",added:"2009-07-29",preferredvalue:"shu",prefix:"ar",macrolanguage:"ar"},
{type:"extlang",subtag:"slf",description:"Swiss-Italian Sign Language",added:"2009-07-29",preferredvalue:"slf",prefix:"sgn"},
{type:"extlang",subtag:"sls",description:"Singapore Sign Language",added:"2009-07-29",preferredvalue:"sls",prefix:"sgn"},
{type:"extlang",subtag:"sqk",description:"Albanian Sign Language",added:"2012-08-12",preferredvalue:"sqk",prefix:"sgn"},
{type:"extlang",subtag:"sqs",description:"Sri Lankan Sign Language",added:"2009-07-29",preferredvalue:"sqs",prefix:"sgn"},
{type:"extlang",subtag:"ssh",description:"Shihhi Arabic",added:"2009-07-29",preferredvalue:"ssh",prefix:"ar",macrolanguage:"ar"},
{type:"extlang",subtag:"ssp",description:"Spanish Sign Language",added:"2009-07-29",preferredvalue:"ssp",prefix:"sgn"},
{type:"extlang",subtag:"ssr",description:"Swiss-French Sign Language",added:"2009-07-29",preferredvalue:"ssr",prefix:"sgn"},
{type:"extlang",subtag:"svk",description:"Slovakian Sign Language",added:"2009-07-29",preferredvalue:"svk",prefix:"sgn"},
{type:"extlang",subtag:"swc",description:"Congo Swahili",added:"2009-07-29",preferredvalue:"swc",prefix:"sw",macrolanguage:"sw"},
{type:"extlang",subtag:"swh",description:"Swahili (individual language), Kiswahili",added:"2009-07-29",preferredvalue:"swh",prefix:"sw",macrolanguage:"sw"},
{type:"extlang",subtag:"swl",description:"Swedish Sign Language",added:"2009-07-29",preferredvalue:"swl",prefix:"sgn"},
{type:"extlang",subtag:"syy",description:"Al-Sayyid Bedouin Sign Language",added:"2009-07-29",preferredvalue:"syy",prefix:"sgn"},
{type:"extlang",subtag:"tmw",description:"Temuan",added:"2009-07-29",preferredvalue:"tmw",prefix:"ms",macrolanguage:"ms"},
{type:"extlang",subtag:"tse",description:"Tunisian Sign Language",added:"2009-07-29",preferredvalue:"tse",prefix:"sgn"},
{type:"extlang",subtag:"tsm",description:"Turkish Sign Language, Türk İşaret Dili",added:"2009-07-29",preferredvalue:"tsm",prefix:"sgn"},
{type:"extlang",subtag:"tsq",description:"Thai Sign Language",added:"2009-07-29",preferredvalue:"tsq",prefix:"sgn"},
{type:"extlang",subtag:"tss",description:"Taiwan Sign Language",added:"2009-07-29",preferredvalue:"tss",prefix:"sgn"},
{type:"extlang",subtag:"tsy",description:"Tebul Sign Language",added:"2009-07-29",preferredvalue:"tsy",prefix:"sgn"},
{type:"extlang",subtag:"tza",description:"Tanzanian Sign Language",added:"2009-07-29",preferredvalue:"tza",prefix:"sgn"},
{type:"extlang",subtag:"ugn",description:"Ugandan Sign Language",added:"2009-07-29",preferredvalue:"ugn",prefix:"sgn"},
{type:"extlang",subtag:"ugy",description:"Uruguayan Sign Language",added:"2009-07-29",preferredvalue:"ugy",prefix:"sgn"},
{type:"extlang",subtag:"ukl",description:"Ukrainian Sign Language",added:"2009-07-29",preferredvalue:"ukl",prefix:"sgn"},
{type:"extlang",subtag:"uks",description:"Urubú-Kaapor Sign Language, Kaapor Sign Language",added:"2009-07-29",preferredvalue:"uks",prefix:"sgn"},
{type:"extlang",subtag:"urk",description:"Urak Lawoi'",added:"2009-07-29",preferredvalue:"urk",prefix:"ms",macrolanguage:"ms"},
{type:"extlang",subtag:"uzn",description:"Northern Uzbek",added:"2009-07-29",preferredvalue:"uzn",prefix:"uz",macrolanguage:"uz"},
{type:"extlang",subtag:"uzs",description:"Southern Uzbek",added:"2009-07-29",preferredvalue:"uzs",prefix:"uz",macrolanguage:"uz"},
{type:"extlang",subtag:"vgt",description:"Vlaamse Gebarentaal, Flemish Sign Language",added:"2009-07-29",preferredvalue:"vgt",prefix:"sgn"},
{type:"extlang",subtag:"vkk",description:"Kaur",added:"2009-07-29",preferredvalue:"vkk",prefix:"ms",macrolanguage:"ms"},
{type:"extlang",subtag:"vkt",description:"Tenggarong Kutai Malay",added:"2009-07-29",preferredvalue:"vkt",prefix:"ms",macrolanguage:"ms"},
{type:"extlang",subtag:"vsi",description:"Moldova Sign Language",added:"2009-07-29",preferredvalue:"vsi",prefix:"sgn"},
{type:"extlang",subtag:"vsl",description:"Venezuelan Sign Language",added:"2009-07-29",preferredvalue:"vsl",prefix:"sgn"},
{type:"extlang",subtag:"vsv",description:"Valencian Sign Language, Llengua de signes valenciana",added:"2009-07-29",preferredvalue:"vsv",prefix:"sgn"},
{type:"extlang",subtag:"wuu",description:"Wu Chinese",added:"2009-07-29",preferredvalue:"wuu",prefix:"zh",macrolanguage:"zh"},
{type:"extlang",subtag:"xki",description:"Kenyan Sign Language",added:"2009-07-29",preferredvalue:"xki",prefix:"sgn"},
{type:"extlang",subtag:"xml",description:"Malaysian Sign Language",added:"2009-07-29",preferredvalue:"xml",prefix:"sgn"},
{type:"extlang",subtag:"xmm",description:"Manado Malay",added:"2009-07-29",preferredvalue:"xmm",prefix:"ms",macrolanguage:"ms"},
{type:"extlang",subtag:"xms",description:"Moroccan Sign Language",added:"2009-07-29",preferredvalue:"xms",prefix:"sgn"},
{type:"extlang",subtag:"yds",description:"Yiddish Sign Language",added:"2009-07-29",deprecated:"2015-02-12",prefix:"sgn"},
{type:"extlang",subtag:"ygs",description:"Yolŋu Sign Language",added:"2014-02-28",preferredvalue:"ygs",prefix:"sgn"},
{type:"extlang",subtag:"yhs",description:"Yan-nhaŋu Sign Language",added:"2015-04-17",preferredvalue:"yhs",prefix:"sgn"},
{type:"extlang",subtag:"ysl",description:"Yugoslavian Sign Language",added:"2009-07-29",preferredvalue:"ysl",prefix:"sgn"},
{type:"extlang",subtag:"yue",description:"Yue Chinese, Cantonese",added:"2009-07-29",preferredvalue:"yue",prefix:"zh",macrolanguage:"zh"},
{type:"extlang",subtag:"zib",description:"Zimbabwe Sign Language",added:"2009-07-29",preferredvalue:"zib",prefix:"sgn"},
{type:"extlang",subtag:"zlm",description:"Malay (individual language)",added:"2009-07-29",preferredvalue:"zlm",prefix:"ms",macrolanguage:"ms"},
{type:"extlang",subtag:"zmi",description:"Negeri Sembilan Malay",added:"2009-07-29",preferredvalue:"zmi",prefix:"ms",macrolanguage:"ms"},
{type:"extlang",subtag:"zsl",description:"Zambian Sign Language",added:"2009-07-29",preferredvalue:"zsl",prefix:"sgn"},
{type:"extlang",subtag:"zsm",description:"Standard Malay",added:"2009-07-29",preferredvalue:"zsm",prefix:"ms",macrolanguage:"ms"},
]