var macrospec = {
// given a macrolanguage, point to the more specific tag that represents the predominant variety
"jrb": {'code':"aju", 'name':"Moroccan Judeo-Arabic"},
"sq": {'code': "als", 'name':"Albanian, Tosk"},
"ar": {'code': "arb", 'name':"Standard Arabic"},
"ay": {'code': "ayr", 'name':"Aymara, Central"},
"az": {'code': "azj", 'name':"Azerbaijani, North"},
"bal": {'code': "bcc", 'name':"Balochi, Southern"},
"bik": {'code': "bcl", 'name':"Bicolano, Central"},
"luy": {'code': "bxk", 'name':"Lubukusu"},
"bua": {'code': "bxr", 'name':"Buriat, Russia"},
"syr": {'code': "cld", 'name':"Chaldean Neo-Aramaic"},
"zh": {'code': "cmn", 'name':"Mandarin Chinese"},
"cr": {'code': "cwd", 'name':"Cree, Woods"},
"doi": {'code': "dgo", 'name':"Dogri"},
"mwr": {'code': "dhd", 'name':"Dhundari"},
"din": {'code': "dik", 'name':"Southwestern Dinka"},
"zza": {'code': "diq", 'name':"Dimli"},
"et": {'code': "ekk", 'name':"Standard Estonian"},
"man": {'code': "emk", 'name':"Maninkakan, Eastern"},
"ik": {'code': "esk", 'name':"Northwest Alaska Inupiatun"},
"ak": {'code': "fat/tw", 'name':"Fanti/Twi"},
//"ak": {'code': "tw", 'name':"Twi"},
"ful": {'code': "fuc", 'name':"Pular"},
"om": {'code': "gaz", 'name':"Oromo, West Central"},
"grb": {'code': "gbo", 'name':"Northern Grebo"},
"gon": {'code': "gno", 'name':"Northern Gondi"},
"gn": {'code': "gug", 'name':"Paraguayan Guarani"},
"gba": {'code': "gya", 'name':"Northwest Gbaya"},
"hai": {'code': "hdn", 'name':"Northern Haida"},
"hmn": {'code': "hea", 'name':"Northern Qiandong Miao"},
"iu": {'code': "ike", 'name':"Eastern Canadian Inuktitut"},
"ku": {'code': "kmr", 'name':"Northern Kurdish"},
"kr": {'code': "knc", 'name':"Central Kanuri"},
"kg": {'code': "kng", 'name':"Koongo"},
"kok": {'code': "knn", 'name':"Konkani (individual language)"},
"kv": {'code': "kpv", 'name':"Komi-Zyrian"},
"chm": {'code': "mhr", 'name':"Eastern Mari"},
"raj": {'code': "mup", 'name':"Malvi"},
"mn": {'code': "mvf", 'name':"Mongolian, Peripheral"},
"no": {'code': "nb", 'name':"Norwegian Bokmal"},
"oj": {'code': "ojg", 'name':"Ojibwa, Eastern"},
"ps": {'code': "pbu", 'name':"Pashto, Northern"},
"fa": {'code': "pes/prs", 'name':"Western Farsi/Dari"},
"mg": {'code': "plt", 'name':"Malagasy, Plateau"},
"lah": {'code': "pnb", 'name':"Western Panjabi"},
//"fa": {'code': "prs", 'name':"Dari"},
"qu": {'code': "qxp", 'name':"Quechua, Puno"},
"rom": {'code': "rmy", 'name':"Romani, Vlax"},
"kln": {'code': "spy", 'name':"Sabaot"},
"sc": {'code': "src", 'name':"Sardinian, Logudorese"},
"sh": {'code': "sr", 'name':"Serbian"},
"sw": {'code': "swh", 'name':"Swahili (individual language)"},
"tmh": {'code': "ttq", 'name':"Tamajaq, Tawallammat"},
"del": {'code': "umu", 'name':"Munsee"},
"uz": {'code': "uzn", 'name':"Northern Uzbek"},
"kpe": {'code': "xpe", 'name':"Kpelle, Liberia"},
"den": {'code': "xsl", 'name':"Slavey, South"},
"yi": {'code': "ydd", 'name':"Yiddish, Eastern"},
"zap": {'code': "zai", 'name':"Zapotec, Isthmus"},
"ms": {'code': "zsm", 'name':"Standard Malay"},
"za": {'code': "zyb", 'name':"Yongbei Zhuang"}
};

var specmacro = {
// give a predominant variety, point to the macrolanguage
"aju": {'code':"jrb", 'name':"Judeo-Arabic"},
"als": {'code':"sq", 'name':"Albanian"},
"arb": {'code':"ar", 'name':"Arabic"},
"ayr": {'code':"ay", 'name':"Aymara"},
"azj": {'code':"az", 'name':"Azerbaijani"},
"bcc": {'code':"bal", 'name':"Baluchi"},
"bcl": {'code':"bik", 'name':"Bikol"},
"bxk": {'code':"luy", 'name':"Luyia"},
"bxr": {'code':"bua", 'name':"Buriat"},
"cld": {'code':"syr", 'name':"Syriac"},
"cmn": {'code':"zh", 'name':"Chinese"},
"cwd": {'code':"cr", 'name':"Cree"},
"dgo": {'code':"doi", 'name':"Dogri (macrolanguage)"},
"dhd": {'code':"mwr", 'name':"Marwari"},
"dik": {'code':"din", 'name':"Dinka"},
"diq": {'code':"zza", 'name':"Zaza"},
"ekk": {'code':"et", 'name':"Estonian"},
"emk": {'code':"man", 'name':"Mandingo"},
"esk": {'code':"ik", 'name':"Inupiaq"},
"fat": {'code':"ak", 'name':"Akan"},
"fuc": {'code':"ful", 'name':"Fulah"},
"gaz": {'code':"om", 'name':"Oromo"},
"gbo": {'code':"grb", 'name':"Grebo"},
"gno": {'code':"gon", 'name':"Gondi"},
"gug": {'code':"gn", 'name':"Guarani"},
"gya": {'code':"gba", 'name':"Gbaya (Central African Republic)"},
"hdn": {'code':"hai", 'name':"Haida"},
"hea": {'code':"hmn", 'name':"Hmong"},
"ike": {'code':"iu", 'name':"Inuktitut"},
"kmr": {'code':"ku", 'name':"Kurdish"},
"knc": {'code':"kr", 'name':"Kanuri"},
"kng": {'code':"kg", 'name':"Kongo"},
"knn": {'code':"kok", 'name':"Konkani"},
"kpv": {'code':"kv", 'name':"Komi"},
"mhr": {'code':"chm", 'name':"Mari (Russia)"},
"mup": {'code':"raj", 'name':"Rajasthani"},
"mvf": {'code':"mn", 'name':"Mongolian"},
"nb": {'code':"no", 'name':"Norwegian"},
"ojg": {'code':"oj", 'name':"Ojibwa"},
"pbu": {'code':"ps", 'name':"Pushto"},
"pes": {'code':"fa", 'name':"Persian"},
"plt": {'code':"mg", 'name':"Malagasy"},
"pnb": {'code':"lah", 'name':"Lahnda"},
"prs": {'code':"fa", 'name':"Persian"},
"qxp": {'code':"qu", 'name':"Quechua"},
"rmy": {'code':"rom", 'name':"Romany"},
"spy": {'code':"kln", 'name':"Kalenjin"},
"src": {'code':"sc", 'name':"Sardinian"},
"sr": {'code':"sh", 'name':"Serbo-Croatian"},
"swh": {'code':"sw", 'name':"Swahili"},
"ttq": {'code':"tmh", 'name':"Tamashek"},
"tw": {'code':"ak", 'name':"Akan"},
"umu": {'code':"del", 'name':"Delaware"},
"uzn": {'code':"uz", 'name':"Uzbek"},
"xpe": {'code':"kpe", 'name':"Kpelle"},
"xsl": {'code':"den", 'name':"Slave (Athapascan)"},
"ydd": {'code':"yi", 'name':"Yiddish"},
"zai": {'code':"zap", 'name':"Zapotec"},
"zsm": {'code':"ms", 'name':"Malay"},
"zyb": {'code':"za", 'name':"Zhuang"}
};


