var scripts = [{type:"script",subtag:"Adlm",description:"Adlam",added:"2014-12-11"},
{type:"script",subtag:"Afak",description:"Afaka",added:"2011-01-07"},
{type:"script",subtag:"Aghb",description:"Caucasian Albanian",added:"2012-11-01"},
{type:"script",subtag:"Ahom",description:"Ahom, Tai Ahom",added:"2013-12-02"},
{type:"script",subtag:"Arab",description:"Arabic",added:"2005-10-16"},
{type:"script",subtag:"Aran",description:"Arabic (Nastaliq variant)",added:"2014-12-11"},
{type:"script",subtag:"Armi",description:"Imperial Aramaic",added:"2007-12-05"},
{type:"script",subtag:"Armn",description:"Armenian",added:"2005-10-16"},
{type:"script",subtag:"Avst",description:"Avestan",added:"2007-07-28"},
{type:"script",subtag:"Bali",description:"Balinese",added:"2005-10-16"},
{type:"script",subtag:"Bamu",description:"Bamum",added:"2009-07-30"},
{type:"script",subtag:"Bass",description:"Bassa Vah",added:"2010-04-10"},
{type:"script",subtag:"Batk",description:"Batak",added:"2005-10-16"},
{type:"script",subtag:"Beng",description:"Bengali, Bangla",added:"2005-10-16"},
{type:"script",subtag:"Bhks",description:"Bhaiksuki",added:"2015-07-24"},
{type:"script",subtag:"Blis",description:"Blissymbols",added:"2005-10-16"},
{type:"script",subtag:"Bopo",description:"Bopomofo",added:"2005-10-16"},
{type:"script",subtag:"Brah",description:"Brahmi",added:"2005-10-16"},
{type:"script",subtag:"Brai",description:"Braille",added:"2005-10-16"},
{type:"script",subtag:"Bugi",description:"Buginese",added:"2005-10-16"},
{type:"script",subtag:"Buhd",description:"Buhid",added:"2005-10-16"},
{type:"script",subtag:"Cakm",description:"Chakma",added:"2007-12-05"},
{type:"script",subtag:"Cans",description:"Unified Canadian Aboriginal Syllabics",added:"2005-10-16"},
{type:"script",subtag:"Cari",description:"Carian",added:"2006-07-21"},
{type:"script",subtag:"Cham",description:"Cham",added:"2005-10-16"},
{type:"script",subtag:"Cher",description:"Cherokee",added:"2005-10-16"},
{type:"script",subtag:"Cirt",description:"Cirth",added:"2005-10-16"},
{type:"script",subtag:"Copt",description:"Coptic",added:"2005-10-16"},
{type:"script",subtag:"Cprt",description:"Cypriot",added:"2005-10-16"},
{type:"script",subtag:"Cyrl",description:"Cyrillic",added:"2005-10-16"},
{type:"script",subtag:"Cyrs",description:"Cyrillic (Old Church Slavonic variant)",added:"2005-10-16"},
{type:"script",subtag:"Deva",description:"Devanagari, Nagari",added:"2005-10-16"},
{type:"script",subtag:"Dogr",description:"Dogra",added:"2017-01-13"},
{type:"script",subtag:"Dsrt",description:"Deseret, Mormon",added:"2005-10-16"},
{type:"script",subtag:"Dupl",description:"Duployan shorthand, Duployan stenography",added:"2010-08-16"},
{type:"script",subtag:"Egyd",description:"Egyptian demotic",added:"2005-10-16"},
{type:"script",subtag:"Egyh",description:"Egyptian hieratic",added:"2005-10-16"},
{type:"script",subtag:"Egyp",description:"Egyptian hieroglyphs",added:"2005-10-16"},
{type:"script",subtag:"Elba",description:"Elbasan",added:"2010-08-16"},
{type:"script",subtag:"Ethi",description:"Ethiopic, Geʻez, Ge'ez",added:"2005-10-16"},
{type:"script",subtag:"Geok",description:"Khutsuri (Asomtavruli and Nuskhuri)",added:"2005-10-16"},
{type:"script",subtag:"Geor",description:"Georgian (Mkhedruli and Mtavruli)",added:"2005-10-16"},
{type:"script",subtag:"Glag",description:"Glagolitic",added:"2005-10-16"},
{type:"script",subtag:"Gong",description:"Gunjala Gondi",added:"2017-01-13"},
{type:"script",subtag:"Gonm",description:"Masaram Gondi",added:"2017-01-13"},
{type:"script",subtag:"Goth",description:"Gothic",added:"2005-10-16"},
{type:"script",subtag:"Gran",description:"Grantha",added:"2009-12-09"},
{type:"script",subtag:"Grek",description:"Greek",added:"2005-10-16"},
{type:"script",subtag:"Gujr",description:"Gujarati",added:"2005-10-16"},
{type:"script",subtag:"Guru",description:"Gurmukhi",added:"2005-10-16"},
{type:"script",subtag:"Hanb",description:"Han with Bopomofo (alias for Han + Bopomofo)",added:"2016-02-08"},
{type:"script",subtag:"Hang",description:"Hangul, Hangŭl, Hangeul",added:"2005-10-16"},
{type:"script",subtag:"Hani",description:"Han, Hanzi, Kanji, Hanja",added:"2005-10-16"},
{type:"script",subtag:"Hano",description:"Hanunoo, Hanunóo",added:"2005-10-16"},
{type:"script",subtag:"Hans",description:"Han (Simplified variant)",added:"2005-10-16"},
{type:"script",subtag:"Hant",description:"Han (Traditional variant)",added:"2005-10-16"},
{type:"script",subtag:"Hatr",description:"Hatran",added:"2013-12-02"},
{type:"script",subtag:"Hebr",description:"Hebrew",added:"2005-10-16"},
{type:"script",subtag:"Hira",description:"Hiragana",added:"2005-10-16"},
{type:"script",subtag:"Hluw",description:"Anatolian Hieroglyphs, Luwian Hieroglyphs, Hittite Hieroglyphs",added:"2011-12-28"},
{type:"script",subtag:"Hmng",description:"Pahawh Hmong",added:"2005-10-16"},
{type:"script",subtag:"Hrkt",description:"Japanese syllabaries (alias for Hiragana + Katakana)",added:"2005-10-16"},
{type:"script",subtag:"Hung",description:"Old Hungarian, Hungarian Runic",added:"2005-10-16"},
{type:"script",subtag:"Inds",description:"Indus, Harappan",added:"2005-10-16"},
{type:"script",subtag:"Ital",description:"Old Italic (Etruscan, Oscan, etc.)",added:"2005-10-16"},
{type:"script",subtag:"Jamo",description:"Jamo (alias for Jamo subset of Hangul)",added:"2016-02-08"},
{type:"script",subtag:"Java",description:"Javanese",added:"2005-10-16"},
{type:"script",subtag:"Jpan",description:"Japanese (alias for Han + Hiragana + Katakana)",added:"2006-07-21"},
{type:"script",subtag:"Jurc",description:"Jurchen",added:"2011-01-07"},
{type:"script",subtag:"Kali",description:"Kayah Li",added:"2005-10-16"},
{type:"script",subtag:"Kana",description:"Katakana",added:"2005-10-16"},
{type:"script",subtag:"Khar",description:"Kharoshthi",added:"2005-10-16"},
{type:"script",subtag:"Khmr",description:"Khmer",added:"2005-10-16"},
{type:"script",subtag:"Khoj",description:"Khojki",added:"2011-08-16"},
{type:"script",subtag:"Kitl",description:"Khitan large script",added:"2014-12-11"},
{type:"script",subtag:"Kits",description:"Khitan small script",added:"2014-12-11"},
{type:"script",subtag:"Knda",description:"Kannada",added:"2005-10-16"},
{type:"script",subtag:"Kore",description:"Korean (alias for Hangul + Han)",added:"2007-07-05"},
{type:"script",subtag:"Kpel",description:"Kpelle",added:"2010-04-10"},
{type:"script",subtag:"Kthi",description:"Kaithi",added:"2007-12-05"},
{type:"script",subtag:"Lana",description:"Tai Tham, Lanna",added:"2006-07-21"},
{type:"script",subtag:"Laoo",description:"Lao",added:"2005-10-16"},
{type:"script",subtag:"Latf",description:"Latin (Fraktur variant)",added:"2005-10-16"},
{type:"script",subtag:"Latg",description:"Latin (Gaelic variant)",added:"2005-10-16"},
{type:"script",subtag:"Latn",description:"Latin",added:"2005-10-16"},
{type:"script",subtag:"Leke",description:"Leke",added:"2015-07-24"},
{type:"script",subtag:"Lepc",description:"Lepcha, Róng",added:"2005-10-16"},
{type:"script",subtag:"Limb",description:"Limbu",added:"2005-10-16"},
{type:"script",subtag:"Lina",description:"Linear A",added:"2005-10-16"},
{type:"script",subtag:"Linb",description:"Linear B",added:"2005-10-16"},
{type:"script",subtag:"Lisu",description:"Lisu, Fraser",added:"2009-03-13"},
{type:"script",subtag:"Loma",description:"Loma",added:"2010-04-10"},
{type:"script",subtag:"Lyci",description:"Lycian",added:"2006-07-21"},
{type:"script",subtag:"Lydi",description:"Lydian",added:"2006-07-21"},
{type:"script",subtag:"Mahj",description:"Mahajani",added:"2012-11-01"},
{type:"script",subtag:"Maka",description:"Makasar",added:"2017-01-13"},
{type:"script",subtag:"Mand",description:"Mandaic, Mandaean",added:"2005-10-16"},
{type:"script",subtag:"Mani",description:"Manichaean",added:"2007-07-28"},
{type:"script",subtag:"Marc",description:"Marchen",added:"2014-12-11"},
{type:"script",subtag:"Maya",description:"Mayan hieroglyphs",added:"2005-10-16"},
{type:"script",subtag:"Medf",description:"Medefaidrin, Oberi Okaime, Oberi Ɔkaimɛ",added:"2017-01-13"},
{type:"script",subtag:"Mend",description:"Mende Kikakui",added:"2010-04-10"},
{type:"script",subtag:"Merc",description:"Meroitic Cursive",added:"2009-12-09"},
{type:"script",subtag:"Mero",description:"Meroitic Hieroglyphs",added:"2005-10-16"},
{type:"script",subtag:"Mlym",description:"Malayalam",added:"2005-10-16"},
{type:"script",subtag:"Modi",description:"Modi, Moḍī",added:"2013-12-02"},
{type:"script",subtag:"Mong",description:"Mongolian",added:"2005-10-16"},
{type:"script",subtag:"Moon",description:"Moon, Moon code, Moon script, Moon type",added:"2007-01-26"},
{type:"script",subtag:"Mroo",description:"Mro, Mru",added:"2011-01-07"},
{type:"script",subtag:"Mtei",description:"Meitei Mayek, Meithei, Meetei",added:"2007-01-26"},
{type:"script",subtag:"Mult",description:"Multani",added:"2013-12-02"},
{type:"script",subtag:"Mymr",description:"Myanmar, Burmese",added:"2005-10-16"},
{type:"script",subtag:"Narb",description:"Old North Arabian, Ancient North Arabian",added:"2010-04-10"},
{type:"script",subtag:"Nbat",description:"Nabataean",added:"2010-04-10"},
{type:"script",subtag:"Newa",description:"Newa, Newar, Newari, Nepāla lipi",added:"2016-01-04"},
{type:"script",subtag:"Nkgb",description:"Nakhi Geba, 'Na-'Khi ²Ggŏ-¹baw, Naxi Geba",added:"2009-03-13"},
{type:"script",subtag:"Nkoo",description:"N’Ko, N'Ko",added:"2005-10-16"},
{type:"script",subtag:"Nshu",description:"Nüshu",added:"2011-01-07"},
{type:"script",subtag:"Ogam",description:"Ogham",added:"2005-10-16"},
{type:"script",subtag:"Olck",description:"Ol Chiki, Ol Cemet', Ol, Santali",added:"2006-07-21"},
{type:"script",subtag:"Orkh",description:"Old Turkic, Orkhon Runic",added:"2009-07-30"},
{type:"script",subtag:"Orya",description:"Oriya, Odia",added:"2005-10-16"},
{type:"script",subtag:"Osge",description:"Osage",added:"2014-12-11"},
{type:"script",subtag:"Osma",description:"Osmanya",added:"2005-10-16"},
{type:"script",subtag:"Palm",description:"Palmyrene",added:"2010-04-10"},
{type:"script",subtag:"Pauc",description:"Pau Cin Hau",added:"2013-12-02"},
{type:"script",subtag:"Perm",description:"Old Permic",added:"2005-10-16"},
{type:"script",subtag:"Phag",description:"Phags-pa",added:"2005-10-16"},
{type:"script",subtag:"Phli",description:"Inscriptional Pahlavi",added:"2007-12-05"},
{type:"script",subtag:"Phlp",description:"Psalter Pahlavi",added:"2007-12-05"},
{type:"script",subtag:"Phlv",description:"Book Pahlavi",added:"2007-07-28"},
{type:"script",subtag:"Phnx",description:"Phoenician",added:"2005-10-16"},
{type:"script",subtag:"Piqd",description:"Klingon (KLI pIqaD)",added:"2016-01-04"},
{type:"script",subtag:"Plrd",description:"Miao, Pollard",added:"2005-10-16"},
{type:"script",subtag:"Prti",description:"Inscriptional Parthian",added:"2007-12-05"},
{type:"script",subtag:"Qaaa..Qabx",description:"Private use",added:"2005-10-16"},
{type:"script",subtag:"Rjng",description:"Rejang, Redjang, Kaganga",added:"2006-10-17"},
{type:"script",subtag:"Roro",description:"Rongorongo",added:"2005-10-16"},
{type:"script",subtag:"Runr",description:"Runic",added:"2005-10-16"},
{type:"script",subtag:"Samr",description:"Samaritan",added:"2007-07-28"},
{type:"script",subtag:"Sara",description:"Sarati",added:"2005-10-16"},
{type:"script",subtag:"Sarb",description:"Old South Arabian",added:"2009-07-30"},
{type:"script",subtag:"Saur",description:"Saurashtra",added:"2006-07-21"},
{type:"script",subtag:"Sgnw",description:"SignWriting",added:"2006-10-17"},
{type:"script",subtag:"Shaw",description:"Shavian, Shaw",added:"2005-10-16"},
{type:"script",subtag:"Shrd",description:"Sharada, Śāradā",added:"2011-01-07"},
{type:"script",subtag:"Sidd",description:"Siddham, Siddhaṃ, Siddhamātṛkā",added:"2013-12-02"},
{type:"script",subtag:"Sind",description:"Khudawadi, Sindhi",added:"2010-08-16"},
{type:"script",subtag:"Sinh",description:"Sinhala",added:"2005-10-16"},
{type:"script",subtag:"Sora",description:"Sora Sompeng",added:"2011-01-07"},
{type:"script",subtag:"Soyo",description:"Soyombo",added:"2017-01-13"},
{type:"script",subtag:"Sund",description:"Sundanese",added:"2006-07-21"},
{type:"script",subtag:"Sylo",description:"Syloti Nagri",added:"2005-10-16"},
{type:"script",subtag:"Syrc",description:"Syriac",added:"2005-10-16"},
{type:"script",subtag:"Syre",description:"Syriac (Estrangelo variant)",added:"2005-10-16"},
{type:"script",subtag:"Syrj",description:"Syriac (Western variant)",added:"2005-10-16"},
{type:"script",subtag:"Syrn",description:"Syriac (Eastern variant)",added:"2005-10-16"},
{type:"script",subtag:"Tagb",description:"Tagbanwa",added:"2005-10-16"},
{type:"script",subtag:"Takr",description:"Takri, Ṭākrī, Ṭāṅkrī",added:"2011-01-07"},
{type:"script",subtag:"Tale",description:"Tai Le",added:"2005-10-16"},
{type:"script",subtag:"Talu",description:"New Tai Lue",added:"2005-10-16"},
{type:"script",subtag:"Taml",description:"Tamil",added:"2005-10-16"},
{type:"script",subtag:"Tang",description:"Tangut",added:"2011-01-07"},
{type:"script",subtag:"Tavt",description:"Tai Viet",added:"2007-12-05"},
{type:"script",subtag:"Telu",description:"Telugu",added:"2005-10-16"},
{type:"script",subtag:"Teng",description:"Tengwar",added:"2005-10-16"},
{type:"script",subtag:"Tfng",description:"Tifinagh, Berber",added:"2005-10-16"},
{type:"script",subtag:"Tglg",description:"Tagalog, Baybayin, Alibata",added:"2005-10-16"},
{type:"script",subtag:"Thaa",description:"Thaana",added:"2005-10-16"},
{type:"script",subtag:"Thai",description:"Thai",added:"2005-10-16"},
{type:"script",subtag:"Tibt",description:"Tibetan",added:"2005-10-16"},
{type:"script",subtag:"Tirh",description:"Tirhuta",added:"2011-08-16"},
{type:"script",subtag:"Ugar",description:"Ugaritic",added:"2005-10-16"},
{type:"script",subtag:"Vaii",description:"Vai",added:"2005-10-16"},
{type:"script",subtag:"Visp",description:"Visible Speech",added:"2005-10-16"},
{type:"script",subtag:"Wara",description:"Warang Citi, Varang Kshiti",added:"2009-12-09"},
{type:"script",subtag:"Wole",description:"Woleai",added:"2011-01-07"},
{type:"script",subtag:"Xpeo",description:"Old Persian",added:"2005-10-16"},
{type:"script",subtag:"Xsux",description:"Sumero-Akkadian cuneiform",added:"2005-10-16"},
{type:"script",subtag:"Yiii",description:"Yi",added:"2005-10-16"},
{type:"script",subtag:"Zanb",description:"Zanabazar Square, Zanabazarin Dörböljin Useg, Xewtee Dörböljin Bicig, Horizontal Square Script",added:"2017-01-13"},
{type:"script",subtag:"Zinh",description:"Code for inherited script",added:"2009-04-03",comments:"Not intended for use as a language subtag"},
{type:"script",subtag:"Zmth",description:"Mathematical notation",added:"2007-12-05"},
{type:"script",subtag:"Zsye",description:"Symbols (Emoji variant)",added:"2016-01-04"},
{type:"script",subtag:"Zsym",description:"Symbols",added:"2007-12-05"},
{type:"script",subtag:"Zxxx",description:"Code for unwritten documents",added:"2005-10-16"},
{type:"script",subtag:"Zyyy",description:"Code for undetermined script",added:"2005-10-16"},
{type:"script",subtag:"Zzzz",description:"Code for uncoded script",added:"2005-10-16"},
]