var variant = [{type:"variant",subtag:"1606nict",description:"Late Middle French (to 1606)",added:"2007-03-20",prefix:"frm",comments:"16th century French as in Jean Nicot, 'Thresor de la langue francoyse', 1606, but also including some French similar to that of Rabelais"},
{type:"variant",subtag:"1694acad",description:"Early Modern French",added:"2007-03-20",prefix:"fr",comments:"17th century French, as catalogued in the 'Dictionnaire de l'académie françoise', 4eme ed. 1694; frequently includes elements of Middle French, as this is a transitional period"},
{type:"variant",subtag:"1901",description:"Traditional German orthography",added:"2005-10-16",prefix:"de"},
{type:"variant",subtag:"1959acad",description:"'Academic' ('governmental') variant of Belarusian as codified in 1959",added:"2008-09-30",prefix:"be"},
{type:"variant",subtag:"1994",description:"Standardized Resian orthography",added:"2007-07-28",prefix:"sl-rozaj, sl-rozaj-biske, sl-rozaj-njiva, sl-rozaj-osojs, sl-rozaj-solba",comments:"For standardized Resian an orthography was published in 1994."},
{type:"variant",subtag:"1996",description:"German orthography of 1996",added:"2005-10-16",prefix:"de"},
{type:"variant",subtag:"abl1943",description:"Orthographic formulation of 1943 - Official in Brazil (Formulário Ortográfico de 1943 - Oficial no Brasil)",added:"2015-05-06",prefix:"pt-BR",comments:"Denotes conventions established by the Academia Brasileira de Letras in 1943 and generally used in Brazil until 2009"},
{type:"variant",subtag:"alalc97",description:"ALA-LC Romanization, 1997 edition",added:"2009-12-09",comments:"Romanizations recommended by the American Library Association and the Library of Congress, in 'ALA-LC Romanization Tables: Transliteration Schemes for Non-Roman Scripts' (1997), ISBN 978-0-8444-0940-5."},
{type:"variant",subtag:"aluku",description:"Aluku dialect, Boni dialect",added:"2009-09-05",prefix:"djk",comments:"Aluku dialect of the 'Busi Nenge Tongo' English-based Creole continuum in Eastern Suriname and Western French Guiana"},
{type:"variant",subtag:"ao1990",description:"Portuguese Language Orthographic Agreement of 1990 (Acordo Ortográfico da Língua Portuguesa de 1990)",added:"2015-05-06",prefix:"pt, gl",comments:"Portuguese orthography conventions established in 1990 but not brought into effect until 2009"},
{type:"variant",subtag:"arevela",description:"Eastern Armenian",added:"2006-09-18",prefix:"hy"},
{type:"variant",subtag:"arevmda",description:"Western Armenian",added:"2006-09-18",prefix:"hy"},
{type:"variant",subtag:"baku1926",description:"Unified Turkic Latin Alphabet (Historical)",added:"2007-04-18",prefix:"az, ba, crh, kk, krc, ky, sah, tk, tt, uz",comments:"Denotes alphabet used in Turkic republics/regions of the former USSR in late 1920s, and throughout 1930s, which aspired to represent equivalent phonemes in a unified fashion. Also known as: New Turkic Alphabet; Birlәşdirilmiş Jeni Tyrk Әlifbasь (Birlesdirilmis Jeni Tyrk Elifbasi); Jaŋalif (Janalif)."},
{type:"variant",subtag:"balanka",description:"The Balanka dialect of Anii",added:"2014-02-15",prefix:"blo",comments:"Balanka is one of 19 Anii dialects."},
{type:"variant",subtag:"barla",description:"The Barlavento dialect group of Kabuverdianu",prefix:"kea",comments:"Barlavento is one of the two main dialect groups of Kabuverdianu.",added:"2013-12-10"},
{type:"variant",subtag:"basiceng",description:"Basic English",added:"2015-12-29",prefix:"en"},
{type:"variant",subtag:"bauddha",description:"Buddhist Hybrid Sanskrit",added:"2010-07-28",prefix:"sa"},
{type:"variant",subtag:"biscayan",description:"Biscayan dialect of Basque",added:"2010-04-13",prefix:"eu"},
{type:"variant",subtag:"biske",description:"The San Giorgio dialect of Resian, The Bila dialect of Resian",added:"2007-07-05",prefix:"sl-rozaj",comments:"The dialect of San Giorgio/Bila is one of the four major local dialects of Resian"},
{type:"variant",subtag:"bohoric",description:"Slovene in Bohorič alphabet",added:"2012-06-27",prefix:"sl",comments:"The subtag represents the alphabet codified by Adam Bohorič in 1584 and used from the first printed Slovene book and up to the mid-19th century."},
{type:"variant",subtag:"boont",description:"Boontling",added:"2006-09-18",prefix:"en",comments:"Jargon embedded in American English"},
{type:"variant",subtag:"colb1945",description:"Portuguese-Brazilian Orthographic Convention of 1945 (Convenção Ortográfica Luso-Brasileira de 1945)",added:"2015-05-06",prefix:"pt",comments:"Portuguese orthography conventions established in 1945, generally in effect until 2009. This reform was not ratified in Brazil."},
{type:"variant",subtag:"cornu",description:"Cornu-English, Cornish English, Anglo-Cornish",added:"2015-12-07",prefix:"en"},
{type:"variant",subtag:"dajnko",description:"Slovene in Dajnko alphabet",added:"2012-06-27",prefix:"sl",comments:"The subtag represents the alphabet codified by Peter Dajnko and used from 1824 to 1839 mostly in Styria (in what is now Eastern Slovenia)."},
{type:"variant",subtag:"ekavsk",description:"Serbian with Ekavian pronunciation",prefix:"sr, sr-Latn, sr-Cyrl",added:"2013-12-02"},
{type:"variant",subtag:"emodeng",description:"Early Modern English (1500-1700)",added:"2012-02-05",prefix:"en"},
{type:"variant",subtag:"fonipa",description:"International Phonetic Alphabet",added:"2006-12-11"},
{type:"variant",subtag:"fonnapa",description:"North American Phonetic Alphabet, Americanist Phonetic Notation",added:"2016-06-24"},
{type:"variant",subtag:"fonupa",description:"Uralic Phonetic Alphabet",added:"2006-12-11"},
{type:"variant",subtag:"fonxsamp",description:"X-SAMPA transcription",added:"2010-10-23",comments:"Indicates that the content is transcribed according to X-SAMPA"},
{type:"variant",subtag:"hepburn",description:"Hepburn romanization",added:"2009-10-01",prefix:"ja-Latn"},
{type:"variant",subtag:"heploc",description:"Hepburn romanization, Library of Congress method",added:"2009-10-01",deprecated:"2010-02-07",preferredvalue:"alalc97",prefix:"ja-Latn-hepburn",comments:"Preferred tag is ja-Latn-alalc97"},
{type:"variant",subtag:"hognorsk",description:"Norwegian in Høgnorsk (High Norwegian) orthography",added:"2010-01-02",prefix:"nn",comments:"Norwegian following Ivar Aasen's orthographical principles, including modern usage."},
{type:"variant",subtag:"ijekavsk",description:"Serbian with Ijekavian pronunciation",prefix:"sr, sr-Latn, sr-Cyrl",added:"2013-12-02"},
{type:"variant",subtag:"itihasa",description:"Epic Sanskrit",added:"2010-07-28",prefix:"sa"},
{type:"variant",subtag:"jauer",description:"Jauer dialect of Romansh",added:"2010-06-29",prefix:"rm",comments:"The spoken dialect of the Val Müstair, which has no written standard."},
{type:"variant",subtag:"jyutping",description:"Jyutping Cantonese Romanization",added:"2010-10-23",prefix:"yue",comments:"Jyutping romanization of Cantonese"},
{type:"variant",subtag:"kkcor",description:"Common Cornish orthography of Revived Cornish",added:"2008-10-14",prefix:"kw"},
{type:"variant",subtag:"kociewie",description:"The Kociewie dialect of Polish",added:"2014-11-27",prefix:"pl",comments:"The dialect of Kociewie is spoken in the region around Starogard Gdański, Tczew and Świecie in northern Poland."},
{type:"variant",subtag:"kscor",description:"Standard Cornish orthography of Revived Cornish, Kernowek Standard",added:"2012-06-27",prefix:"kw"},
{type:"variant",subtag:"laukika",description:"Classical Sanskrit",added:"2010-07-28",prefix:"sa"},
{type:"variant",subtag:"lipaw",description:"The Lipovaz dialect of Resian, The Lipovec dialect of Resian",added:"2007-08-11",prefix:"sl-rozaj",comments:"The dialect of Lipovaz/Lipovec is one of the minor local dialects of Resian"},
{type:"variant",subtag:"luna1918",description:"Post-1917 Russian orthography",added:"2010-10-10",prefix:"ru",comments:"Russian orthography as established by the 1917/1918 orthographic reforms"},
{type:"variant",subtag:"metelko",description:"Slovene in Metelko alphabet",added:"2012-06-27",prefix:"sl",comments:"The subtag represents the alphabet codified by Franc Serafin Metelko and used from 1825 to 1833."},
{type:"variant",subtag:"monoton",description:"Monotonic Greek",added:"2006-12-11",prefix:"el"},
{type:"variant",subtag:"ndyuka",description:"Ndyuka dialect, Aukan dialect",added:"2009-09-05",prefix:"djk",comments:"Ndyuka dialect of the 'Busi Nenge Tongo' English-based Creole continuum in Eastern Suriname and Western French Guiana"},
{type:"variant",subtag:"nedis",description:"Natisone dialect, Nadiza dialect",added:"2005-10-16",prefix:"sl"},
{type:"variant",subtag:"newfound",description:"Newfoundland English",added:"2015-11-25",prefix:"en-CA"},
{type:"variant",subtag:"njiva",description:"The Gniva dialect of Resian, The Njiva dialect of Resian",added:"2007-07-05",prefix:"sl-rozaj",comments:"The dialect of Gniva/Njiva is one of the four major local dialects of Resian"},
{type:"variant",subtag:"nulik",description:"Volapük nulik, Volapük perevidöl, Volapük nulädik, de Jong's Volapük, New Volapük, Revised Volapük, Modern Volapük",added:"2012-01-28",prefix:"vo"},
{type:"variant",subtag:"osojs",description:"The Oseacco dialect of Resian, The Osojane dialect of Resian",added:"2007-07-05",prefix:"sl-rozaj",comments:"The dialect of Oseacco/Osojane is one of the four major local dialects of Resian"},
{type:"variant",subtag:"oxendict",description:"Oxford English Dictionary spelling",added:"2015-04-17",prefix:"en"},
{type:"variant",subtag:"pamaka",description:"Pamaka dialect",added:"2009-09-05",prefix:"djk",comments:"Pamaka dialect of the 'Busi Nenge Tongo' English-based Creole continuum in Eastern Suriname and Western French Guiana"},
{type:"variant",subtag:"petr1708",description:"Petrine orthography",added:"2010-10-10",prefix:"ru",comments:"Russian orthography from the Petrine orthographic reforms of 1708 to the 1917 orthographic reform"},
{type:"variant",subtag:"pinyin",description:"Pinyin romanization",added:"2008-10-14",prefix:"zh-Latn, bo-Latn"},
{type:"variant",subtag:"polyton",description:"Polytonic Greek",added:"2006-12-11",prefix:"el"},
{type:"variant",subtag:"puter",description:"Puter idiom of Romansh",added:"2010-06-29",prefix:"rm",comments:"Puter is one of the five traditional written standards or 'idioms' of the Romansh language."},
{type:"variant",subtag:"rigik",description:"Volapük rigik, Schleyer's Volapük, Original Volapük, Classic Volapük",added:"2012-01-28",prefix:"vo"},
{type:"variant",subtag:"rozaj",description:"Resian, Resianic, Rezijan",added:"2005-10-16",prefix:"sl"},
{type:"variant",subtag:"rumgr",description:"Rumantsch Grischun",added:"2010-06-29",prefix:"rm",comments:"Supraregional Romansh written standard"},
{type:"variant",subtag:"scotland",description:"Scottish Standard English",added:"2007-08-31",prefix:"en"},
{type:"variant",subtag:"scouse",description:"Scouse",added:"2006-09-18",prefix:"en",comments:"English Liverpudlian dialect known as 'Scouse'"},
{type:"variant",subtag:"simple",description:"Simplified form",added:"2015-12-29"},
{type:"variant",subtag:"solba",description:"The Stolvizza dialect of Resian, The Solbica dialect of Resian",added:"2007-07-05",prefix:"sl-rozaj",comments:"The dialect of Stolvizza/Solbica is one of the four major local dialects of Resian"},
{type:"variant",subtag:"sotav",description:"The Sotavento dialect group of Kabuverdianu",prefix:"kea",comments:"Sotavento is one of the two main dialect groups of Kabuverdianu.",added:"2013-12-10"},
{type:"variant",subtag:"surmiran",description:"Surmiran idiom of Romansh",added:"2010-06-29",prefix:"rm",comments:"Surmiran is one of the five traditional written standards or 'idioms' of the Romansh language."},
{type:"variant",subtag:"sursilv",description:"Sursilvan idiom of Romansh",added:"2010-06-29",prefix:"rm",comments:"Sursilvan is one of the five traditional written standards or 'idioms' of the Romansh language."},
{type:"variant",subtag:"sutsilv",description:"Sutsilvan idiom of Romansh",added:"2010-06-29",prefix:"rm",comments:"Sutsilvan is one of the five traditional written standards or 'idioms' of the Romansh language."},
{type:"variant",subtag:"tarask",description:"Belarusian in Taraskievica orthography",added:"2007-04-27",prefix:"be",comments:"The subtag represents Branislau Taraskievic's Belarusian orthography as published in 'Bielaruski klasycny pravapis' by Juras Buslakou, Vincuk Viacorka, Zmicier Sanko, and Zmicier Sauka (Vilnia- Miensk 2005)."},
{type:"variant",subtag:"uccor",description:"Unified Cornish orthography of Revived Cornish",added:"2008-10-14",prefix:"kw"},
{type:"variant",subtag:"ucrcor",description:"Unified Cornish Revised orthography of Revived Cornish",added:"2008-10-14",prefix:"kw"},
{type:"variant",subtag:"ulster",description:"Ulster dialect of Scots",added:"2010-04-10",prefix:"sco"},
{type:"variant",subtag:"unifon",description:"Unifon phonetic alphabet",added:"2013-10-02",prefix:"en, hup, kyh, tol, yur"},
{type:"variant",subtag:"vaidika",description:"Vedic Sanskrit",added:"2010-07-28",prefix:"sa",comments:"The most ancient dialect of Sanskrit used in verse and prose composed until about the 4th century B.C.E."},
{type:"variant",subtag:"valencia",description:"Valencian",added:"2007-03-06",prefix:"ca",comments:"Variety spoken in the 'Comunidad Valenciana' region of Spain, where it is co-official with Spanish."},
{type:"variant",subtag:"vallader",description:"Vallader idiom of Romansh",added:"2010-06-29",prefix:"rm",comments:"Vallader is one of the five traditional written standards or 'idioms' of the Romansh language."},
{type:"variant",subtag:"wadegile",description:"Wade-Giles romanization",added:"2008-10-03",prefix:"zh-Latn"},
]