var charData = {
"\u0901":{n:"DEVANAGARI SIGN CANDRABINDU",m:1,g:"Devanagari"},
"\u0902":{n:"DEVANAGARI SIGN ANUSVARA",m:1,g:"Devanagari"},
"\u0903":{n:"DEVANAGARI SIGN VISARGA",m:1,g:"Devanagari"},
"\u0905":{n:"DEVANAGARI LETTER A",m:0,g:"Devanagari"},
"\u0906":{n:"DEVANAGARI LETTER AA",m:0,g:"Devanagari"},
"\u0908":{n:"DEVANAGARI LETTER II",m:0,g:"Devanagari"},
"\u0915":{n:"DEVANAGARI LETTER KA",m:0,g:"Devanagari"},
"\u0916":{n:"DEVANAGARI LETTER KHA",m:0,g:"Devanagari"},
"\u0917":{n:"DEVANAGARI LETTER GA",m:0,g:"Devanagari"},
"\u0918":{n:"DEVANAGARI LETTER GHA",m:0,g:"Devanagari"},
"\u0919":{n:"DEVANAGARI LETTER NGA",m:0,g:"Devanagari"},
"\u091A":{n:"DEVANAGARI LETTER CA",m:0,g:"Devanagari"},
"\u091C":{n:"DEVANAGARI LETTER JA",m:0,g:"Devanagari"},
"\u091D":{n:"DEVANAGARI LETTER JHA",m:0,g:"Devanagari"},
"\u091E":{n:"DEVANAGARI LETTER NYA",m:0,g:"Devanagari"},
"\u091F":{n:"DEVANAGARI LETTER TTA",m:0,g:"Devanagari"},
"\u0921":{n:"DEVANAGARI LETTER DDA",m:0,g:"Devanagari"},
"\u0924":{n:"DEVANAGARI LETTER TA",m:0,g:"Devanagari"},
"\u0926":{n:"DEVANAGARI LETTER DA",m:0,g:"Devanagari"},
"\u0927":{n:"DEVANAGARI LETTER DHA",m:0,g:"Devanagari"},
"\u0928":{n:"DEVANAGARI LETTER NA",m:0,g:"Devanagari"},
"\u0929":{n:"DEVANAGARI LETTER NNNA",m:0,g:"Devanagari"},
"\u092A":{n:"DEVANAGARI LETTER PA",m:0,g:"Devanagari"},
"\u092B":{n:"DEVANAGARI LETTER PHA",m:0,g:"Devanagari"},
"\u092C":{n:"DEVANAGARI LETTER BA",m:0,g:"Devanagari"},
"\u092E":{n:"DEVANAGARI LETTER MA",m:0,g:"Devanagari"},
"\u092F":{n:"DEVANAGARI LETTER YA",m:0,g:"Devanagari"},
"\u0930":{n:"DEVANAGARI LETTER RA",m:0,g:"Devanagari"},
"\u0931":{n:"DEVANAGARI LETTER RRA",m:0,g:"Devanagari"},
"\u0932":{n:"DEVANAGARI LETTER LA",m:0,g:"Devanagari"},
"\u0934":{n:"DEVANAGARI LETTER LLLA",m:0,g:"Devanagari"},
"\u0936":{n:"DEVANAGARI LETTER SHA",m:0,g:"Devanagari"},
"\u0937":{n:"DEVANAGARI LETTER SSA",m:0,g:"Devanagari"},
"\u0938":{n:"DEVANAGARI LETTER SA",m:0,g:"Devanagari"},
"\u03AB":{n:"DEVANAGARI LETTER HA",m:0,g:"Devanagari"},
"\u093C":{n:"DEVANAGARI SIGN NUKTA",m:1,g:"Devanagari"},
"\u093E":{n:"DEVANAGARI VOWEL SIGN AA",m:1,g:"Devanagari"},
"\u093F":{n:"DEVANAGARI VOWEL SIGN I",m:1,g:"Devanagari"},
"\u0940":{n:"DEVANAGARI VOWEL SIGN II",m:1,g:"Devanagari"},
"\u0941":{n:"DEVANAGARI VOWEL SIGN U",m:1,g:"Devanagari"},
"\u0942":{n:"DEVANAGARI VOWEL SIGN UU",m:1,g:"Devanagari"},
"\u0947":{n:"DEVANAGARI VOWEL SIGN E",m:1,g:"Devanagari"},
"\u094B":{n:"DEVANAGARI VOWEL SIGN O",m:1,g:"Devanagari"},
"\u094D":{n:"DEVANAGARI SIGN VIRAMA",m:1,g:"Devanagari"},
"\u0958":{n:"DEVANAGARI LETTER QA",m:0,g:"Devanagari"},
"\u0964":{n:"DEVANAGARI DANDA",m:0,g:"Devanagari"},
"\u0965":{n:"DEVANAGARI DOUBLE DANDA",m:0,g:"Devanagari"},
"\u0966":{n:"DEVANAGARI DIGIT ZERO",m:0,g:"Devanagari"},
"\u0967":{n:"DEVANAGARI DIGIT ONE",m:0,g:"Devanagari"},
"\u0968":{n:"DEVANAGARI DIGIT TWO",m:0,g:"Devanagari"},
"\u0969":{n:"DEVANAGARI DIGIT THREE",m:0,g:"Devanagari"},
"\u096A":{n:"DEVANAGARI DIGIT FOUR",m:0,g:"Devanagari"},
"\u096B":{n:"DEVANAGARI DIGIT FIVE",m:0,g:"Devanagari"},
"\u096C":{n:"DEVANAGARI DIGIT SIX",m:0,g:"Devanagari"},
"\u096D":{n:"DEVANAGARI DIGIT SEVEN",m:0,g:"Devanagari"},
"\u096E":{n:"DEVANAGARI DIGIT EIGHT",m:0,g:"Devanagari"},
"\u096F":{n:"DEVANAGARI DIGIT NINE",m:0,g:"Devanagari"},
"\u0995":{n:"BENGALI LETTER KA",m:0,g:"Bengali"},
"\u09B7":{n:"BENGALI LETTER SSA",m:0,g:"Bengali"},
"\u09CD":{n:"BENGALI SIGN VIRAMA",m:1,g:"Bengali"},
"\u09E6":{n:"BENGALI DIGIT ZERO",m:0,g:"Bengali"},
"\u09E7":{n:"BENGALI DIGIT ONE",m:0,g:"Bengali"},
"\u09E8":{n:"BENGALI DIGIT TWO",m:0,g:"Bengali"},
"\u09E9":{n:"BENGALI DIGIT THREE",m:0,g:"Bengali"},
"\u09EA":{n:"BENGALI DIGIT FOUR",m:0,g:"Bengali"},
"\u09EB":{n:"BENGALI DIGIT FIVE",m:0,g:"Bengali"},
"\u09EC":{n:"BENGALI DIGIT SIX",m:0,g:"Bengali"},
"\u09ED":{n:"BENGALI DIGIT SEVEN",m:0,g:"Bengali"},
"\u09EE":{n:"BENGALI DIGIT EIGHT",m:0,g:"Bengali"},
"\u09EF":{n:"BENGALI DIGIT NINE",m:0,g:"Bengali"},
"\u0A02":{n:"GURMUKHI SIGN BINDI",m:1,g:"Gurmukhi"},
"\u0A05":{n:"GURMUKHI LETTER A",m:0,g:"Gurmukhi"},
"\u0A06":{n:"GURMUKHI LETTER AA",m:0,g:"Gurmukhi"},
"\u0A07":{n:"GURMUKHI LETTER I",m:0,g:"Gurmukhi"},
"\u0A08":{n:"GURMUKHI LETTER II",m:0,g:"Gurmukhi"},
"\u0A09":{n:"GURMUKHI LETTER U",m:0,g:"Gurmukhi"},
"\u0A0A":{n:"GURMUKHI LETTER UU",m:0,g:"Gurmukhi"},
"\u0A0F":{n:"GURMUKHI LETTER EE",m:0,g:"Gurmukhi"},
"\u0A10":{n:"GURMUKHI LETTER AI",m:0,g:"Gurmukhi"},
"\u0A13":{n:"GURMUKHI LETTER OO",m:0,g:"Gurmukhi"},
"\u0A14":{n:"GURMUKHI LETTER AU",m:0,g:"Gurmukhi"},
"\u0A15":{n:"GURMUKHI LETTER KA",m:0,g:"Gurmukhi"},
"\u0A18":{n:"GURMUKHI LETTER GHA",m:0,g:"Gurmukhi"},
"\u0A21":{n:"GURMUKHI LETTER DDA",m:0,g:"Gurmukhi"},
"\u0A24":{n:"GURMUKHI LETTER TA",m:0,g:"Gurmukhi"},
"\u0A2A":{n:"GURMUKHI LETTER PA",m:0,g:"Gurmukhi"},
"\u0A2E":{n:"GURMUKHI LETTER MA",m:0,g:"Gurmukhi"},
"\u0A30":{n:"GURMUKHI LETTER RA",m:0,g:"Gurmukhi"},
"\u0A32":{n:"GURMUKHI LETTER LA",m:0,g:"Gurmukhi"},
"\u0A33":{n:"GURMUKHI LETTER LLA",m:0,g:"Gurmukhi"},
"\u0A38":{n:"GURMUKHI LETTER SA",m:0,g:"Gurmukhi"},
"\u0A3C":{n:"GURMUKHI SIGN NUKTA",m:1,g:"Gurmukhi"},
"\u0A3E":{n:"GURMUKHI VOWEL SIGN AA",m:1,g:"Gurmukhi"},
"\u0A41":{n:"GURMUKHI VOWEL SIGN U",m:1,g:"Gurmukhi"},
"\u0A4B":{n:"GURMUKHI VOWEL SIGN OO",m:1,g:"Gurmukhi"},
"\u0A5C":{n:"GURMUKHI LETTER RRA",m:0,g:"Gurmukhi"},
"\u0A66":{n:"GURMUKHI DIGIT ZERO",m:0,g:"Gurmukhi"},
"\u0A67":{n:"GURMUKHI DIGIT ONE",m:0,g:"Gurmukhi"},
"\u0A68":{n:"GURMUKHI DIGIT TWO",m:0,g:"Gurmukhi"},
"\u0A69":{n:"GURMUKHI DIGIT THREE",m:0,g:"Gurmukhi"},
"\u0A6A":{n:"GURMUKHI DIGIT FOUR",m:0,g:"Gurmukhi"},
"\u0A6B":{n:"GURMUKHI DIGIT FIVE",m:0,g:"Gurmukhi"},
"\u0A6C":{n:"GURMUKHI DIGIT SIX",m:0,g:"Gurmukhi"},
"\u0A6D":{n:"GURMUKHI DIGIT SEVEN",m:0,g:"Gurmukhi"},
"\u0A6E":{n:"GURMUKHI DIGIT EIGHT",m:0,g:"Gurmukhi"},
"\u0A6F":{n:"GURMUKHI DIGIT NINE",m:0,g:"Gurmukhi"},
"\u0A70":{n:"GURMUKHI TIPPI",m:1,g:"Gurmukhi"},
"\u0A71":{n:"GURMUKHI ADDAK",m:1,g:"Gurmukhi"},
"\u0A72":{n:"GURMUKHI IRI",m:0,g:"Gurmukhi"},
"\u0A73":{n:"GURMUKHI URA",m:0,g:"Gurmukhi"},
"\u0A95":{n:"GUJARATI LETTER KA",m:0,g:"Gujarati"},
"\u0A9F":{n:"GUJARATI LETTER TTA",m:0,g:"Gujarati"},
"\u0AA0":{n:"GUJARATI LETTER TTHA",m:0,g:"Gujarati"},
"\u0ABF":{n:"GUJARATI VOWEL SIGN I",m:1,g:"Gujarati"},
"\u0ACD":{n:"GUJARATI SIGN VIRAMA",m:1,g:"Gujarati"},
"\u0AE6":{n:"GUJARATI DIGIT ZERO",m:0,g:"Gujarati"},
"\u0AE7":{n:"GUJARATI DIGIT ONE",m:0,g:"Gujarati"},
"\u0AE8":{n:"GUJARATI DIGIT TWO",m:0,g:"Gujarati"},
"\u0AE9":{n:"GUJARATI DIGIT THREE",m:0,g:"Gujarati"},
"\u0AEA":{n:"GUJARATI DIGIT FOUR",m:0,g:"Gujarati"},
"\u0AEB":{n:"GUJARATI DIGIT FIVE",m:0,g:"Gujarati"},
"\u0AEC":{n:"GUJARATI DIGIT SIX",m:0,g:"Gujarati"},
"\u0AED":{n:"GUJARATI DIGIT SEVEN",m:0,g:"Gujarati"},
"\u0AEE":{n:"GUJARATI DIGIT EIGHT",m:0,g:"Gujarati"},
"\u0AEF":{n:"GUJARATI DIGIT NINE",m:0,g:"Gujarati"},
"\u0B01":{n:"ORIYA SIGN CANDRABINDU",m:1,g:"Oriya"},
"\u0B02":{n:"ORIYA SIGN ANUSVARA",m:1,g:"Oriya"},
"\u0B05":{n:"ORIYA LETTER A",m:0,g:"Oriya"},
"\u0B06":{n:"ORIYA LETTER AA",m:0,g:"Oriya"},
"\u0B15":{n:"ORIYA LETTER KA",m:0,g:"Oriya"},
"\u0B22":{n:"ORIYA LETTER DDHA",m:0,g:"Oriya"},
"\u0B3C":{n:"ORIYA SIGN NUKTA",m:0,g:"Oriya"},
"\u0B3E":{n:"ORIYA VOWEL SIGN AA",m:1,g:"Oriya"},
"\u0B5C":{n:"ORIYA LETTER RRA",m:0,g:"Oriya"},
"\u0B66":{n:"ORIYA DIGIT ZERO",m:0,g:"Oriya"},
"\u0B67":{n:"ORIYA DIGIT ONE",m:0,g:"Oriya"},
"\u0B68":{n:"ORIYA DIGIT TWO",m:0,g:"Oriya"},
"\u0B69":{n:"ORIYA DIGIT THREE",m:0,g:"Oriya"},
"\u0B6A":{n:"ORIYA DIGIT FOUR",m:0,g:"Oriya"},
"\u0B6B":{n:"ORIYA DIGIT FIVE",m:0,g:"Oriya"},
"\u0B6C":{n:"ORIYA DIGIT SIX",m:0,g:"Oriya"},
"\u0B6D":{n:"ORIYA DIGIT SEVEN",m:0,g:"Oriya"},
"\u0B6E":{n:"ORIYA DIGIT EIGHT",m:0,g:"Oriya"},
"\u0B6F":{n:"ORIYA DIGIT NINE",m:0,g:"Oriya"},
"\u0B83":{n:"TAMIL SIGN VISARGA",m:1,g:"Tamil"},
"\u0B87":{n:"TAMIL LETTER I",m:0,g:"Tamil"},
"\u0B95":{n:"TAMIL LETTER KA",m:0,g:"Tamil"},
"\u0B9A":{n:"TAMIL LETTER CA",m:0,g:"Tamil"},
"\u0B9C":{n:"TAMIL LETTER JA",m:0,g:"Tamil"},
"\u0BA4":{n:"TAMIL LETTER TA",m:0,g:"Tamil"},
"\u0BA8":{n:"TAMIL LETTER NA",m:0,g:"Tamil"},
"\u0BA9":{n:"TAMIL LETTER NNNA",m:0,g:"Tamil"},
"\u0BAA":{n:"TAMIL LETTER PA",m:0,g:"Tamil"},
"\u0BAE":{n:"TAMIL LETTER MA",m:0,g:"Tamil"},
"\u0BB0":{n:"TAMIL LETTER RA",m:0,g:"Tamil"},
"\u0BB8":{n:"TAMIL LETTER SA",m:0,g:"Tamil"},
"\u0BB9":{n:"TAMIL LETTER HA",m:0,g:"Tamil"},
"\u0BBE":{n:"TAMIL VOWEL SIGN AA",m:1,g:"Tamil"},
"\u0BBF":{n:"TAMIL VOWEL SIGN I",m:1,g:"Tamil"},
"\u0BC0":{n:"TAMIL VOWEL SIGN II",m:1,g:"Tamil"},
"\u0BC1":{n:"TAMIL VOWEL SIGN U",m:1,g:"Tamil"},
"\u0BC6":{n:"TAMIL VOWEL SIGN E",m:1,g:"Tamil"},
"\u0BC8":{n:"TAMIL VOWEL SIGN AI",m:1,g:"Tamil"},
"\u0BCA":{n:"TAMIL VOWEL SIGN O",m:1,g:"Tamil"},
"\u0BCC":{n:"TAMIL VOWEL SIGN AU",m:1,g:"Tamil"},
"\u0BCD":{n:"TAMIL SIGN VIRAMA",m:1,g:"Tamil"},
"\u0BD7":{n:"TAMIL AU LENGTH MARK",m:1,g:"Tamil"},
"\u0BE6":{n:"TAMIL DIGIT ZERO",m:0,g:"Tamil"},
"\u0BE7":{n:"TAMIL DIGIT ONE",m:0,g:"Tamil"},
"\u0BE8":{n:"TAMIL DIGIT TWO",m:0,g:"Tamil"},
"\u0BE9":{n:"TAMIL DIGIT THREE",m:0,g:"Tamil"},
"\u0BEA":{n:"TAMIL DIGIT FOUR",m:0,g:"Tamil"},
"\u0BEB":{n:"TAMIL DIGIT FIVE",m:0,g:"Tamil"},
"\u0BEC":{n:"TAMIL DIGIT SIX",m:0,g:"Tamil"},
"\u0BED":{n:"TAMIL DIGIT SEVEN",m:0,g:"Tamil"},
"\u0BEE":{n:"TAMIL DIGIT EIGHT",m:0,g:"Tamil"},
"\u0BEF":{n:"TAMIL DIGIT NINE",m:0,g:"Tamil"},
"\u0BF0":{n:"TAMIL NUMBER TEN",m:0,g:"Tamil"},
"\u0BF1":{n:"TAMIL NUMBER ONE HUNDRED",m:0,g:"Tamil"},
"\u0BF2":{n:"TAMIL NUMBER ONE THOUSAND",m:0,g:"Tamil"},
"\u0C05":{n:"TELUGU LETTER A",m:0,g:"Telugu"},
"\u0C06":{n:"TELUGU LETTER AA",m:0,g:"Telugu"},
"\u0C07":{n:"TELUGU LETTER I",m:0,g:"Telugu"},
"\u0C08":{n:"TELUGU LETTER II",m:0,g:"Telugu"},
"\u0C09":{n:"TELUGU LETTER U",m:0,g:"Telugu"},
"\u0C0A":{n:"TELUGU LETTER UU",m:0,g:"Telugu"},
"\u0C0B":{n:"TELUGU LETTER VOCALIC R",m:0,g:"Telugu"},
"\u0C0E":{n:"TELUGU LETTER E",m:0,g:"Telugu"},
"\u0C0F":{n:"TELUGU LETTER EE",m:0,g:"Telugu"},
"\u0C10":{n:"TELUGU LETTER AI",m:0,g:"Telugu"},
"\u0C12":{n:"TELUGU LETTER O",m:0,g:"Telugu"},
"\u0C13":{n:"TELUGU LETTER OO",m:0,g:"Telugu"},
"\u0C14":{n:"TELUGU LETTER AU",m:0,g:"Telugu"},
"\u0C15":{n:"TELUGU LETTER KA",m:0,g:"Telugu"},
"\u0C3E":{n:"TELUGU VOWEL SIGN AA",m:1,g:"Telugu"},
"\u0C3F":{n:"TELUGU VOWEL SIGN I",m:1,g:"Telugu"},
"\u0C40":{n:"TELUGU VOWEL SIGN II",m:1,g:"Telugu"},
"\u0C41":{n:"TELUGU VOWEL SIGN U",m:1,g:"Telugu"},
"\u0C42":{n:"TELUGU VOWEL SIGN UU",m:1,g:"Telugu"},
"\u0C43":{n:"TELUGU VOWEL SIGN VOCALIC R",m:1,g:"Telugu"},
"\u0C46":{n:"TELUGU VOWEL SIGN E",m:1,g:"Telugu"},
"\u0C47":{n:"TELUGU VOWEL SIGN EE",m:1,g:"Telugu"},
"\u0C48":{n:"TELUGU VOWEL SIGN AI",m:1,g:"Telugu"},
"\u0C4A":{n:"TELUGU VOWEL SIGN O",m:1,g:"Telugu"},
"\u0C4B":{n:"TELUGU VOWEL SIGN OO",m:1,g:"Telugu"},
"\u0C4C":{n:"TELUGU VOWEL SIGN AU",m:1,g:"Telugu"},
"\u0C4D":{n:"TELUGU SIGN VIRAMA",m:1,g:"Telugu"},
"\u0C66":{n:"TELUGU DIGIT ZERO",m:0,g:"Telugu"},
"\u0C67":{n:"TELUGU DIGIT ONE",m:0,g:"Telugu"},
"\u0C68":{n:"TELUGU DIGIT TWO",m:0,g:"Telugu"},
"\u0C69":{n:"TELUGU DIGIT THREE",m:0,g:"Telugu"},
"\u0C6A":{n:"TELUGU DIGIT FOUR",m:0,g:"Telugu"},
"\u0C6B":{n:"TELUGU DIGIT FIVE",m:0,g:"Telugu"},
"\u0C6C":{n:"TELUGU DIGIT SIX",m:0,g:"Telugu"},
"\u0C6D":{n:"TELUGU DIGIT SEVEN",m:0,g:"Telugu"},
"\u0C6E":{n:"TELUGU DIGIT EIGHT",m:0,g:"Telugu"},
"\u0C6F":{n:"TELUGU DIGIT NINE",m:0,g:"Telugu"},
"\u0C82":{n:"KANNADA SIGN ANUSVARA",m:1,g:"Kannada"},
"\u0C83":{n:"KANNADA SIGN VISARGA",m:1,g:"Kannada"},
"\u0C85":{n:"KANNADA LETTER A",m:0,g:"Kannada"},
"\u0C95":{n:"KANNADA LETTER KA",m:0,g:"Kannada"},
"\u0C97":{n:"KANNADA LETTER GA",m:0,g:"Kannada"},
"\u0CA4":{n:"KANNADA LETTER TA",m:0,g:"Kannada"},
"\u0CA8":{n:"KANNADA LETTER NA",m:0,g:"Kannada"},
"\u0CAA":{n:"KANNADA LETTER PA",m:0,g:"Kannada"},
"\u0CAF":{n:"KANNADA LETTER YA",m:0,g:"Kannada"},
"\u0CB0":{n:"KANNADA LETTER RA",m:0,g:"Kannada"},
"\u0CB2":{n:"KANNADA LETTER LA",m:0,g:"Kannada"},
"\u0CB8":{n:"KANNADA LETTER SA",m:0,g:"Kannada"},
"\u0CB9":{n:"KANNADA LETTER HA",m:0,g:"Kannada"},
"\u0CBE":{n:"KANNADA VOWEL SIGN AA",m:1,g:"Kannada"},
"\u0CBF":{n:"KANNADA VOWEL SIGN I",m:1,g:"Kannada"},
"\u0CC1":{n:"KANNADA VOWEL SIGN U",m:1,g:"Kannada"},
"\u0CCB":{n:"KANNADA VOWEL SIGN OO",m:1,g:"Kannada"},
"\u0CCD":{n:"KANNADA SIGN VIRAMA",m:1,g:"Kannada"},
"\u0CD5":{n:"KANNADA LENGTH MARK",m:1,g:"Kannada"},
"\u0CDE":{n:"KANNADA LETTER FA",m:0,g:"Kannada"},
"\u0CE6":{n:"KANNADA DIGIT ZERO",m:0,g:"Kannada"},
"\u0CE7":{n:"KANNADA DIGIT ONE",m:0,g:"Kannada"},
"\u0CE8":{n:"KANNADA DIGIT TWO",m:0,g:"Kannada"},
"\u0CE9":{n:"KANNADA DIGIT THREE",m:0,g:"Kannada"},
"\u0CEA":{n:"KANNADA DIGIT FOUR",m:0,g:"Kannada"},
"\u0CEB":{n:"KANNADA DIGIT FIVE",m:0,g:"Kannada"},
"\u0CEC":{n:"KANNADA DIGIT SIX",m:0,g:"Kannada"},
"\u0CED":{n:"KANNADA DIGIT SEVEN",m:0,g:"Kannada"},
"\u0CEE":{n:"KANNADA DIGIT EIGHT",m:0,g:"Kannada"},
"\u0CEF":{n:"KANNADA DIGIT NINE",m:0,g:"Kannada"},
"\u0D15":{n:"MALAYALAM LETTER KA",m:0,g:"Malayalam"},
"\u0D4D":{n:"MALAYALAM SIGN VIRAMA",m:1,g:"Malayalam"},
"\u0D66":{n:"MALAYALAM DIGIT ZERO",m:0,g:"Malayalam"},
"\u0D67":{n:"MALAYALAM DIGIT ONE",m:0,g:"Malayalam"},
"\u0D68":{n:"MALAYALAM DIGIT TWO",m:0,g:"Malayalam"},
"\u0D69":{n:"MALAYALAM DIGIT THREE",m:0,g:"Malayalam"},
"\u0D6A":{n:"MALAYALAM DIGIT FOUR",m:0,g:"Malayalam"},
"\u0D6B":{n:"MALAYALAM DIGIT FIVE",m:0,g:"Malayalam"},
"\u0D6C":{n:"MALAYALAM DIGIT SIX",m:0,g:"Malayalam"},
"\u0D6D":{n:"MALAYALAM DIGIT SEVEN",m:0,g:"Malayalam"},
"\u0D6E":{n:"MALAYALAM DIGIT EIGHT",m:0,g:"Malayalam"},
"\u0D6F":{n:"MALAYALAM DIGIT NINE",m:0,g:"Malayalam"},
"\u200C":{n:"ZERO WIDTH NON-JOINER",m:0,g:"General Punctuation"},
"\u200D":{n:"ZERO WIDTH JOINER",m:0,g:"General Punctuation"},

end: {}
}